### ISSUE TITLE
keine Vertikale Scrollbalken

### ISSUE THREAD

**Issue by raschy** [MiRo1310/ioBroker.telegram-menu#103]
Ich vermisse in der Konfiguration des Adapters sowohl bei der Navigation als auch bei den Aktions im unteren Bereich einen vertikalen Scrollbalken. Auf nem großen Monitor hab ich den noch nicht vermisst, aber bei mehreren Einträgen und nem kleinen Laptop - keine Chance da dran zu kommen. Versucht in Edge und Chrome und bin auch zurückgegangen auf Version 1.4.0. Wahrscheinlich war es noch nie drin und ist niemandem aufgefallen.

**Comment by MiRo1310** [comment]
Du meinst einen horizontalen Scrollbalken, der die Breite regelt. (Vertikal von oben nach unten ist auf jeden Fall drin. )
Ja das stimmt der war noch nie drin. 
Werde ich anpassen

**Comment by raschy** [comment]
Ich meinte schon den vertikalen, womit ich die Einträge hoch und runter schieben kann. Horizontal hat mir noch nicht gefehlt.

**Comment by Willi-Wunder** [comment]
Hi, im Firefox habe ich die Balken sowohl in der Übersicht als auch beim Aufruf des Menüs (Getstate). 

Im Edge Browser wird der Balken nicht angezeigt, ich kann aber mit dem Mausrad trotzdem scrollen.
![Scrollbalken](https://github.com/MiRo1310/ioBroker.telegram-menu/assets/77007062/5f0f774d-56e6-42da-a6f5-a1dc7d78c90a)
Beim Aufruf bei Getstate erscheint der Scrollbalken auch beim Edge Browser.
![Scrollbalken GETSTATE](https://github.com/MiRo1310/ioBroker.telegram-menu/assets/77007062/3d7f3a5a-605a-467c-b932-1bba82509ca6)

**Comment by MiRo1310** [comment]
@raschy dann kann das Problem eigentlich nur noch bei deinem Browser in irgendeiner Art und Weise liegen. Warum auch immer

**Comment by raschy** [comment]
Mag sein, dass meine Augen nicht mehr die Besten sind. Aber verschiedene Rechner, verschiedene Browser (ausser Firefox) haben den Scrollbalken nicht. Aber wie WilliWunder sagte, mit dem Scrollrad gehts ja. Also: keine Energie mehr reinstecken!

**Comment by MiRo1310** [comment]
Achso du hast nur den scrollbalken nicht, kannst aber scrollen. Das kann gut möglich sein. Schaue ich nach

**Comment by raschy** [comment]
Bin ich selbst (Touchpad am Laptop) nicht drauf gekommen. Aber nach dem Hinweis von WilliWunder am PC probiert. Funzt, auch ohne den Balken zu sehen.
