### ISSUE TITLE
Http-request possible ?

### ISSUE THREAD

**Issue by Seqway** [MiRo1310/ioBroker.telegram-menu#104]
I am running the latest 1.6.1 beta version.

I would like to ask if it is possible to make a http-request for example to get a picture (live) from my camera or doorbird.

Manually I do it in the browser for example with such a request:

`http://a.b.c.d/bha-api/image.cgi?http-user=mydefinedusername&http-password=mydefinedpassword`

or

`http://a.b.c.dcgi-bin/api.cgi?cmd=Snap&channel=0&rs=wuuPhkmUCeI9WG7C&user=myusername&password=mypassword&from=1605251176726&to=1605272776727&height=13000&now=1605272776729&interval=%24__interval&sample=Not%20escaped%3A%20%24__interval&since=-1`

Is such a request in principle possible ? 
in general it is a feature request.

**Comment by MiRo1310** [comment]
@Seqway Ich habe den Http Request eingebaut, einmal bitte von Github installieren und testen. Ich habe leider nichts was ich mit Authentification laden kann, ein einfacher Request um ein Bild von Google  zu laden geht. Wenn alles soweit funktioniert, wäre ich dankbar über eine Rückmeldung

**Comment by Seqway** [comment]
@MiRo1310 
Okay ich hab das jetzt mal versucht. Aber wie muss ich den http request denn hinten angeben ?
Einfach nur mit image.cgi (siehe oben) ?

**Comment by MiRo1310** [comment]
Nimm als url alles bis zum ?

**Comment by Seqway** [comment]
Okay gab ich gemacht. Leider kommt nichts :-( soll ich dir irgendwie ein Log schicken?

**Comment by MiRo1310** [comment]
Ja kannst du machen, kommt denn ein error ?

**Comment by Seqway** [comment]
Nein kommt kein error im Log für telegram-menu

**Comment by MiRo1310** [comment]
Ich schaue mir das noch mal an. Aber schwer zu testen wenn ich nichts habe wo ich mich authentifizieren kann.

**Comment by MiRo1310** [comment]
Poste aber trotzdem mal das debug log

**Comment by MiRo1310** [comment]
@Seqway Ich habe die Funktion noch mal etwas geändert und jetzt sollten auch ein paar Errors im log auftauchen wenn der request nicht durchläuft. Bitte dann das log wenn möglich hier posten.

**Comment by Seqway** [comment]
> @Seqway 
> Was ich noch vergessen habe zu sagen, der Ordner der in den Einstellungen steht, muss vollen schreibzugriff haben.

Was heisst vollen Zugriff ? Und welcher ordner ist gemeint ?

**Comment by MiRo1310** [comment]
@Seqway in den Einstellungen steht als default /opt/iobroker meine ich. Dieser Ordner muss vollen schreibzugriff haben.  Der Befehl unter Linux ist "chmod 777 <filename or Directory>"

Unter filename: egal wie das heißt Photo.jpg oder was auch immer

**Comment by MiRo1310** [comment]
@Seqway hast du noch mal testen können?

**Comment by MiRo1310** [comment]
Wird erstmal geschlossen da keine Info mehr kommt
