### ISSUE TITLE
Wunsch: Startmenü beim Start frei definieren

### ISSUE THREAD

**Issue by Willi-Wunder** [MiRo1310/ioBroker.telegram-menu#105]
Wenn der Adapter beim Speichern neugestartet wird, öffnet er bei Telegram das **zuletzt** bearbeitete Menü. Könnte man ein Menü frei definieren, welches zuerst immer geöffnet wird, wenn der Adapter neu gestartet wird?

**Comment by MiRo1310** [comment]
Also ich habe nochmals geschaut, wenn ich speichere wird immer das startmenü geöffnet, so habe ich das auch im Code geschrieben, das kann eigentlich nicht anders sein. Daher war ja meine Überlegung das ich die Startseite frei wählbar mache indem man diese auch draggable macht und somit die jede andere Row dahin schieben kann

**Comment by Willi-Wunder** [comment]
In meiner Overview steht Startseite not linked. 
![Startseite](https://github.com/MiRo1310/ioBroker.telegram-menu/assets/77007062/0734e9f2-0904-4ce9-aeef-6f3662d4104c)

Kann es daran liegen? Was bedeutet das genau? Wie hast du gedacht das man die Startseite genau festlegen kann?

**Comment by MiRo1310** [comment]
Rufst du denn von irgendwo die Startseite auf? Not linked , soll eigentlich bedeuten das einen trigger hast der aber keinem Button zugeordnet ist. Unused schwarz ist wenn du einen Button hast der noch keine Aktion ausführt. So der Plan.

**Comment by Willi-Wunder** [comment]
Die Startseite hatte ich zu Beginn manuell aufgerufen, danach komme ich mit dem zurück Button immer wieder dort hin. Vor dem zurück Button hatte ich meine Menüs mit der "Startseite" verlinkt gehabt.
Die schwarzen Buttons sind klar, die 3 unused Buttons mit "Start2","Ende1+2" sind noch nicht zugeordnet, da dass mit dem Schreiben der Werte noch nicht geklappt hat. Vielleicht hast du hierzu noch eine Idee wie ich das machen könnte. 
Version 1.6.2 ist bereits installiert.

**Comment by MiRo1310** [comment]
Und was ist mit dem Menü speichern? 

Zu welchem Problem könnte ich evtl behilflich sein?

**Comment by MiRo1310** [comment]
Das kann ich nicht verstehen warum das so ist

**Comment by Willi-Wunder** [comment]
Muss das aktive Menü evtl. dann auch Startseite wie der Auslöser heißen? Irgendwie hab ich es aber anscheinend noch nicht verstanden. Ich hab doch hier 5 Navigationen in der Menüliste stehen. Jeweils dir grüne Zeile ist meine entsprechende Navigation. Woher weiß er nun, welche meine Standard Startseite sein soll?

**Comment by MiRo1310** [comment]
Ich glaube ich weiß wo das Problem ist. 

Die Startseite ist immer die grüne Zeile. Wenn ich recht in der Annahme gehe hast du verschiedene Menüs die nicht miteinander verknüpft sind. 
Normalerweise gibt es nur ein hauptmenu welches auf alle anderen zugreift. 
Normalerweise ist es gedacht das im zweiten Menü die grüne Zeile deaktiviert wird. Infos auch in der Doku. 
Und jetzt erklärt sich auch warum immer die Seite aufgerufen wird die geändert wurde.

**Comment by Willi-Wunder** [comment]
Also wenn ich das jetzt richtig verstanden habe sollte es dann so gemacht werden:
Vorher:
![StartMenü1](https://github.com/MiRo1310/ioBroker.telegram-menu/assets/77007062/4f609101-813e-4443-a760-d3f8dc59ebb6)
![StartMenü3](https://github.com/MiRo1310/ioBroker.telegram-menu/assets/77007062/3146012a-585f-4622-b5ff-0873aeb6c5e9)
![StartMenü4](https://github.com/MiRo1310/ioBroker.telegram-menu/assets/77007062/3b6ae85e-f17f-44a2-87a4-2d732894f02f)

Neu:
![StartMenü_neu_Startseite](https://github.com/MiRo1310/ioBroker.telegram-menu/assets/77007062/bcb63ee0-ccb9-479c-9015-61747dd8c024)
![StartMenü_neu_Rollo](https://github.com/MiRo1310/ioBroker.telegram-menu/assets/77007062/524e1b29-1cea-40a4-a3bf-66ae6c0088e2)
![StartMenü_neu_Wohnhaus](https://github.com/MiRo1310/ioBroker.telegram-menu/assets/77007062/de4877fa-5dd4-46ad-bb3d-45af1111913e)

Die Startseite steht im Overview mit "not linked" drin. Womit soll ich diese denn verlinken? Startseite ist doch der Auslöser womit das Menü erstmalig in Telegram aufgerufen werden soll. Steh ich immer noch auf der Leitung? 
Wenn ich jetzt ein Startmenü für einen anderen Benutzer erstellen möchte, schreibe ich das dann bei Menü bei mir mit rein? Eine neue grüne Zeile würde jetzt wieder das gleiche Problem bei mir auslösen, richtig?

**Comment by MiRo1310** [comment]
Hi. Ja so ist es richtig. Startseite ist Not linked weil du von nirgendwo anders dort hin zurück gehst. Ich habe jetzt gerade nicht auf dem Schirm ob du das mit zurück machst. Aber das spielt ja auch keine Rolle. Wenn du einem zweiten User eine eigene Startseite gibst wird ihm seine Startseite beim speichern geschickt. Wenn ihr beide die gleiche Startseite habt wird euch beiden diese geschickt. Vorausgesetzt das die checkbox in den Einstellungen angehakt ist " send After Restart " oder so ähnlich.
