### ISSUE TITLE
Change Befehl Fehler bei / in mehreren Status Abfragen

### ISSUE THREAD

**Issue by JimmyBondi** [MiRo1310/ioBroker.telegram-menu#106]
Ja genau das ist es, wie gesagt für jeden status ein change, die id durchlaufen eine schleife die erste id sucht nach dem ersten aufkommen des change, du kannst auch beide change am ende machen, das erste ist für id 1 und das zweite für id2. sinn macht es , denn du könntest 2 verschiedene ids abrufen, einmal number und z.b. boolean, so bist du flexibel und kannst für beide es sinnvoll einstellen.

_Originally posted by @MiRo1310 in https://github.com/MiRo1310/ioBroker.telegram-menu/issues/86#issuecomment-1848976553_
            

Ich habe ebenfalls ein Problem bei mehreren Status Abfragen über die Navigation.

<code>
<b><u>Balkon : </u></b>
Balkontür: {status:zigbee.0.00158d0000000000.opened} change{"true":"<u><b><i>geöffnet !!!</i></b></u>","false":"geschlossen"}
Aussenbeleuchtung: {status:zigbee.0.ec1bbd0000000000.state} change{"true":"<b>an</b>","false":"aus"}
Wandlampe : {status:zigbee.0.2c11650000000000.available} change{"true":"<b>an</b>","false":"aus"}
Wandlampe Brightness : <b>{status:zigbee.0.2c11650000000000.brightness}</b>
Aussentemperatur: {status:zigbee.0.00124b0000000000.temperature} °C
Luftfeuchtigkeit: {status:zigbee.0.00124b0000000000.humidity} %
Helligkeit: {status:zigbee.0.04cf8c0000000000.illuminance} Lux
</code>

Setze ich die drei betreffenden Zeilen an den Anfang, funktioniert es.
Dabei spielt es dann auch keine Rolle, ob die changes direkt hinter der Zeile oder unten angefügt werden.

<code>
Balkon : 
Balkontür: geschlossen 
Aussenbeleuchtung: aus 
Wandlampe : aus 
Wandlampe Brightness : 20
Aussentemperatur: 5.14 °C
Luftfeuchtigkeit: 99.99 %
Helligkeit: 57 Lux
</code>

Ziehe ich die Zeilen auseinander oder setzte diese z.Bsp. ans Ende, kommt es zu Fehlern :

<code>
Balkon : 
Aussentemperatur: undefined °C
Luftfeuchtigkeit: undefined %
Helligkeit: undefined Lux
Wandlampe Brightness : 20
Balkontür: false 
Aussenbeleuchtung: false 
Wandlampe : false
</code>

Versions:
1.5.1 stable

**Comment by JimmyBondi** [comment]
Eine Idee wäre vielleicht, ein GetState anzulegen, welches über das Textfeld der Navigation,  mit z.Bsp: GetState=balkon_status, abgerufen werden kann. (ähnlich wie functions=Licht)

**Comment by MiRo1310** [comment]
Auch hier solltest du erstmal den Adapter komplett updaten und noch mal berichten ob das Problem noch da ist, denn da könnte sich auch schon etwas geändert haben

**Comment by JimmyBondi** [comment]
> Auch hier solltest du erstmal den Adapter komplett updaten und noch mal berichten ob das Problem noch da ist, denn da könnte sich auch schon etwas geändert haben

Das Problem besteht bei der latest 1.6.1 weiterhin.
Egal, ob ich die Changes direkt in der Zeile oder unten anfüge.


`Balkon : 
Balkontür: geschlossen 
Aussentemperatur: undefined °C
Luftfeuchtigkeit: undefined %
Helligkeit: 236 Lux
Aussenbeleuchtung: false 
Wandlampe : false 
Wandlampe Brightness : 10`

**Comment by MiRo1310** [comment]
Bitte von Github über die Katze installieren
