### ISSUE TITLE
drei Menü Einträge in einer Reihe funktioniert nur mit workaround

### ISSUE THREAD

**Issue by JimmyBondi** [MiRo1310/ioBroker.telegram-menu#107]
Wenn ich in einem Untermenü lediglich drei Menü Einträge in einer Reihe haben möchte, erscheinen die drei Elemente untereinander. Hier am Beispiel Balkon :

![1704396011564-navigation](https://github.com/MiRo1310/ioBroker.telegram-menu/assets/11534219/2e50b35c-f37e-40ec-8113-ec54da270d0c)

![1704396097246-telegram_navi](https://github.com/MiRo1310/ioBroker.telegram-menu/assets/11534219/e11bd60d-a049-4ae2-aecc-f710055399cb)

Setze ich && am Ende der Zeile, funktioniert es.

**Versions:**  
1.5.1 stable

**Comment by MiRo1310** [comment]
Dann läuft doch alles und nichts ist zu tun

**Comment by JimmyBondi** [comment]
> Dann läuft doch alles und nichts ist zu tun

Im Grunde nicht, da die Kommata durch && ersetzt werden und erst durch hinzufügen einer neuen (leeren) Zeile korrekt interpretiert werden.
Natürlich kann ich damit leben, wenn man es einmal weiß :)

**Comment by MiRo1310** [comment]
Ich baue dazu was ein.
