### ISSUE TITLE
Fehler bei der Funktion menu:back

### ISSUE THREAD

**Issue by JimmyBondi** [MiRo1310/ioBroker.telegram-menu#108]
Folgende EInträge sind in der Navigation :

![1704407632838-back](https://github.com/MiRo1310/ioBroker.telegram-menu/assets/11534219/a1f63cea-554d-4648-a763-36c0d160673c)

- Navigiere ich von der Übersicht in Räume, komme ich mit Back NICHT zurück zur Übersicht
- Navigiere ich von der Übersicht in Räume zu Balkon, komme ich, mit Back, zurück zu Räume, bekomme jedoch den Statustext von der Übersicht (Willkommen)

Grundsätzlich wird mir immer der Statustext vom vorletzten Menü angezeigt wird.
Ich komme nicht mehr zu meiner Startseite (Übersicht) zurück, sondern hänge im Untermenü fest.

Im Log habe ich folgende Fehlermeldung, beim Versuch zurück zur Startseite zu kommen :

`2024-01-06 10:56:36.602 - error: telegram-menu.0 (22873) Error subMenu: "Cannot read properties of undefined (reading 'text')TypeError: Cannot read properties of undefined (reading 'text')\n at switchBack (/opt/iobroker/node_modules/iobroker.telegram-menu/lib/js/backMenu.js:51:79)\n at subMenu (/opt/iobroker/node_modules/iobroker.telegram-menu/lib/js/subMenu.js:302:19)\n at async callSubMenu (/opt/iobroker/node_modules/iobroker.telegram-menu/lib/js/subMenu.js:44:23)\n at async processData (/opt/iobroker/node_modules/iobroker.telegram-menu/lib/js/processData.js:156:21)\n at async checkEveryMenuForData (/opt/iobroker/node_modules/iobroker.telegram-menu/lib/js/processData.js:59:4)\n at async TelegramMenu. (/opt/iobroker/node_modules/iobroker.telegram-menu/main.js:222:28)"`

**Versions:**  
1.5.1 stable

**Comment by MiRo1310** [comment]
Am besten mal die neuste latest bzw. von Github installieren und noch mal testen, ich habe da schon mal was dran geändert, ich habe es jetzt gerade mal ausführlich getestet und ich habe da jetzt keinen Fehler gefunden
