### ISSUE TITLE
Vereinfachung erstellung der Submenüs

### ISSUE THREAD

**Issue by JimmyBondi** [MiRo1310/ioBroker.telegram-menu#109]
Das anlegen von SetState Submenüs Bsp. menu:percent10:TRIGGER: könnte vereinfacht werden, in dem diese nicht erst über die Navigation erstellt werden, sonder direkt im SetState selbst. 

Denkbar wäre hier im Bereich Wert, das Submenü zu definieren

![submenu](https://github.com/MiRo1310/ioBroker.telegram-menu/assets/11534219/a82e2a14-2a8c-4b71-8b35-774f38001a75)

Daduch würde man sich einen zwischenschritt sparen, sowie das definieren eines zusätzlichen triggers und verschafft etwas mehr Übersicht.

**Comment by MiRo1310** [comment]
Das ist sicherlich wahr. Das würde dann ein Breaking change und jeder User müsste alles umbauen. 
Es fing alles klein an und da habe ich an diese Ausmaße nicht gedacht. Ich werde mir das aber anschauen.

**Comment by MiRo1310** [comment]
Werde ich nicht umsetzen da dann andere Probleme auftauchen
