### ISSUE TITLE
Parsemode unter "Get State" ohne Funktion

### ISSUE THREAD

**Issue by quorle** [MiRo1310/ioBroker.telegram-menu#110]
Irgendwie funktioniert der Parsemode unter "Get State" nicht. 

![Unbenannt](https://github.com/MiRo1310/ioBroker.telegram-menu/assets/38273154/96b83c0a-3d25-44cd-baa5-845fe9e5988b)

![Unbenannt_1](https://github.com/MiRo1310/ioBroker.telegram-menu/assets/38273154/d30c3e17-6458-407c-bbf7-a6eb4b7b221c)

**Versions:**  
 - Adapter version: 1.6.1
 - JS-Controller version: 5.0.17
 - Node version: 18.19.0

**Comment by MiRo1310** [comment]
![grafik](https://github.com/MiRo1310/ioBroker.telegram-menu/assets/68854794/bd1d3f1c-7af0-4a19-8823-87577771dda2)
![grafik](https://github.com/MiRo1310/ioBroker.telegram-menu/assets/68854794/79c9822a-6672-4adb-904d-2b5e90d8b539)
Vielleicht einmal den Parse Mode deaktivieren und wieder aktivieren, ich das gerade hier so getestet und wie du siehst geht es

**Comment by quorle** [comment]
Danke für deine Antwort. Habe gerade alles versucht, auch den Server neu gestartet, jedoch ohne Erfolg. bleibt beim alten

**Comment by MiRo1310** [comment]
Hast auch schon von Github über die Katze aktualisiert? Das solltest du auf jeden Fall machen

**Comment by JimmyBondi** [comment]
Habe das gleiche Problem. Update über die Katze, hat nicht geholfen.
Mir ist noch ein anderes Parsing Problem aufgefallen. Nehme an, dass das ggf zusammen hängt.
Wenn ich mit menu:back zwischen Menülisten switche, funktioniert das Parsing ebenfalls nicht und die im Text hinterlegten Statusabfragen, werden nicht ausgeführt und stattdessen als text ausgegeben.

**Comment by MiRo1310** [comment]
Okay gut zu wissen. Schaue ich mal drüber

**Comment by JimmyBondi** [comment]
Mir ist auch aufgefallen, dass sich der parsing button, in der Navigation, zum Teil nicht mehr aktivieren lässt.

**Comment by MiRo1310** [comment]
@JimmyBondi @quorle ich habe mal eine Änderung hoch geladen, probiert mal aus, jetzt geht der parseMode auch beim zurück gehen

**Comment by JimmyBondi** [comment]
Beim Navigieren funktioniert es jetzt prima !

Hab da noch etwas in Verbindung mit SetDynamicValue entdeckt.
Nach Eingabe und absenden eines Textes, erscheint wieder der Text aus der Naviagtion und dieser ist ebenfalls nicht korrekt.

![LG_Navigation](https://github.com/MiRo1310/ioBroker.telegram-menu/assets/11534219/29850ae2-992f-4811-9726-c1ad9355e7c6)

![LG_SetState](https://github.com/MiRo1310/ioBroker.telegram-menu/assets/11534219/007b0844-acda-42df-a7ad-9955d0a18c83)

![LG_Telegram](https://github.com/MiRo1310/ioBroker.telegram-menu/assets/11534219/aa88d47d-cc02-434c-b7c5-a0e02aebf6bc)

**Comment by MiRo1310** [comment]
Okay das ist genau der Punkt den ich gesucht habe, schaue ich mir direkt an

**Comment by JimmyBondi** [comment]
Wobei hier jetzt noch die Frage ist, ob das Verhalten : Absenden von Text = erneutes Aufrufen der Navigation
überhaupt so vorgesehen ist oder war.

**Comment by MiRo1310** [comment]
@JimmyBondi ich kann im Moment das Verhalten auch so nicht nachstelllen

**Comment by MiRo1310** [comment]
@quorle Ich habe etliche Versuche unternommen um dieses nach zu stellen. Evtl mal parse Mode raus nehmen speichern und wieder rein machen. Evtl kann das helfen

@JimmyBondi auch dein Problem habe ich noch mal mir angeschaut, bei mir sieht es so aus
![grafik](https://github.com/MiRo1310/ioBroker.telegram-menu/assets/68854794/462ac71c-6fac-4c47-9e12-45b8b8f530f2)
ich öffne das menu mit dem Button setDynamicValue die Aufforderung kommt das ich einen Wert eingeben soll, wenn ich dieses mache verschwindet das Menu und ich muss es über das kleine Viereck wieder holen, aber es wird keine weitere Anfrage gestellt

**Comment by JimmyBondi** [comment]
Wie sieht denn der setDynamicValue Aufruf bei Dir aus?

**Comment by MiRo1310** [comment]
@JimmyBondi so sieht der aus, also eigentlich alles wie bei dir, würde ich sagen
![grafik](https://github.com/MiRo1310/ioBroker.telegram-menu/assets/68854794/c4553854-bece-4e59-a612-2a102a424817)

**Comment by MiRo1310** [comment]
@quorle hast du das schon mal versucht mit dem parse Mode aus zu schalten und dann wieder ein zu schalten?

**Comment by JimmyBondi** [comment]
Und in der Naviagtion hast Du ebenfalls einen text angegeben ?
Habe jetzt exakt die Zeile, wie bei Dir und es wird bei mir nicht korrekt dargestellt.
Mir wird zum Beispiel auch der Text "Wert wurde auf && gesetzt" gar nicht ausgegeben.

**Comment by MiRo1310** [comment]
Das ist der Aufruf!
![grafik](https://github.com/MiRo1310/ioBroker.telegram-menu/assets/68854794/5d28096f-2219-4dd8-9595-4d838b5d6c78)

**Comment by MiRo1310** [comment]
So sieht es dann aus 
![grafik](https://github.com/MiRo1310/ioBroker.telegram-menu/assets/68854794/d06d4643-d88f-4925-90df-8d81030a2aaf)

**Comment by JimmyBondi** [comment]
ja seltsam.
Wobei bei Dir ebenfalls die Bestätigung "Wert wurde auf 4567 gesetzt" fehlt

**Comment by MiRo1310** [comment]
Ja das kommt dadurch das ich den Wert nicht mit ack true gesetzt hatte, habe ich jetzt noch mal damit gemacht, dann sieht es so aus
![grafik](https://github.com/MiRo1310/ioBroker.telegram-menu/assets/68854794/b2a2a0fd-2516-4d24-90b6-ace22a3aece9)

![grafik](https://github.com/MiRo1310/ioBroker.telegram-menu/assets/68854794/e68481fb-cfbe-4513-80f7-12fa08e8e5f2)

**Comment by JimmyBondi** [comment]
Mit ack true kommt die Rückmeldung bei mir dann auch und zusätzlich wird wieder der Text aus der Navigation angezeigt.
Aber egal. Es bleibt jetzt wie es ist :)

**Comment by MiRo1310** [comment]
@JimmyBondi , ich habe das gerade noch mal in meinem Produktivsystem getestet, da bekomme ich auch den Text aus der Navigation, ich werde mir das noch mal anschauen.

**Comment by MiRo1310** [comment]
@JimmyBondi so das Problem sollte gelöst sein. Bitte von Github installieren und testen
@quorle Kannst du bitte auch noch eimal von Github installieren und testen?

**Comment by JimmyBondi** [comment]
Der Text aus der Navigation wird weiterhin angezeigt, aber das parsen funktioniert jetzt.

**Comment by MiRo1310** [comment]
Ja genau der Text wird angezeigt, bei mir auch.

**Comment by MiRo1310** [comment]
@quorle Besteht das Problem immer noch?

**Comment by quorle** [comment]
@MiRo1310 bis jetzt klappt alles.
