### ISSUE TITLE
Wunsch: bei "menu:dynSwitch" einen Status als Name einfügen

### ISSUE THREAD

**Issue by JimmyBondi** [MiRo1310/ioBroker.telegram-menu#111]
Würde sich bei `menu:dynSwitch[Name1|value1, Name2|value2, Value3]:TRIGGER:LenghtOfRow:`
auch ein Status als Name einfügen lassen ?
Dadurch wäre es u.A. möglich, bei einem Internet Radio oder Smart TV, den jeweiligen Sendernamen als Button zu nutzen.

**Comment by MiRo1310** [comment]
@JimmyBondi du möchtest also den wert eines Datenpunktes da eintragen? Im Prinzip muss man sich dann überlegen wie man die id dadrin platziert. Man könnte zum Beispiel sagen das der Name durch id%0.userdata.abc ersetzt werden muss.

**Comment by JimmyBondi** [comment]
Gute Idee.
Oder um es mehr einheitlich zu machen {status:0.userdata.abc}

**Comment by MiRo1310** [comment]
Ja normalerweise geht das nicht weil da auch ein Doppelpunkt drin ist, aber dazu ist mir gerade eine Idee gekommen. Werde ich so umsetzen

**Comment by MiRo1310** [comment]
Es ist wie alles andere jetzt {status:'id':'ID':true}
