### ISSUE TITLE
Mapping einer Range

### ISSUE THREAD

**Issue by JimmyBondi** [MiRo1310/ioBroker.telegram-menu#113]
Bei einigen dimmbaren Lampen wird die Brightness mit Werten von 0 bis 255 gesetzt.
Dies würde ich z.bsp mit menu:percent gerne umwandeln in 0 bis 100 %.

**Comment by MiRo1310** [comment]
Erkläre das genauer.

**Comment by JimmyBondi** [comment]
Die Idee ist, dass ich ein SubMenü habe mit einer Spanne von 0% bis 100%, welches die Werte von 0 bis 255 entspricht.
Also 255 = 100% oder 125 = 50% usw.

**Comment by MiRo1310** [comment]
Warum nicht einfach Menu number und dann von 0 bis 255 und dann einem Stepp von 25.5 ? Z.b. ?

**Comment by JimmyBondi** [comment]
Ich werde das dann mit dynSwitch umsetzen. Wenn das Template einmal erstellt ist, kann ich es beliebig kopieren und anwenden.
