### ISSUE TITLE
`Telegram >1.15.6 required

### ISSUE THREAD

**Issue by Negalein** [MiRo1310/ioBroker.telegram-menu#12]
`startInstance system.adapter.telegram-menu.0 Adapter dependency not fulfilled on any host: required adapter "telegram" has wrong version. Installed "1.15.6", required ">1.15.6"!`

bekomme bei der aktuellen Version obigen Fehler.
Telegram = 1.15.6 (dies ist die aktuelle Version)

**Comment by MiRo1310** [comment]
@Negalein jetzt sollte es passen, bitte einmal neu von Github installieren

**Comment by Negalein** [comment]
> @Negalein jetzt sollte es passen, bitte einmal neu von Github installieren

Danke, diese Meldung ist nun weg! :)

PS: gibt es im Forum schon einen Thread? Sind einige Fragen zur Bedienung, usw.

**Comment by MiRo1310** [comment]
Nein noch nicht, schreibe erstmal hier
