### ISSUE TITLE
Seit gestern Geht nichts mehr. 

### ISSUE THREAD

**Issue by quorle** [MiRo1310/ioBroker.telegram-menu#122]
Ich beziehe meine Adapter aus dem „Latest“ Repo. Gestern wurden keine Updates gemacht, aber mir viel dass das Telegram Menü nicht mehr funktioniert. Siehe LOG. Anscheinend kennt er den Befehl /n nicht mehr. 

`
telegram-menu.0 | 2024-02-21 08:11:37.871 | error | Error processData: "Cannot read properties of undefined (reading 'Zurück')"
-- | -- | -- | --
telegram-menu.0 | 2024-02-21 08:11:37.871 | error | "TypeError: Cannot read properties of undefined (reading 'Zurück')\n at processData (/opt/iobroker/node_modules/iobroker.telegram-menu/lib/js/processData.js:148:15)\n at checkEveryMenuForData (/opt/iobroker/node_modules/iobroker.telegram-menu/lib/js/processData.js:59:10)\n at async TelegramMenu.<anonymous> (/opt/iobroker/node_modules/iobroker.telegram-menu/main.js:226:28)"

`

**Versions:**  
 - Adapter version: v1.6.2
 - Node version: v18.19.1

**Comment by MiRo1310** [comment]
Kannst du mir mal genau zeigen wo du das /n benutzt hast damit ich es nachstellen kann?

**Comment by quorle** [comment]
Hier ist mir das Problem aufgefallen (siehe Bilder).
Nach einem Neustart des Adapters funktioniert alles wieder für ein paar Stunden. Danach wieder das gleiche Problem.
Vielleicht liegt es an der Admin-Version 6.14.1, seit dieser Version ist mir der Fehler aufgefallen.

![Unbenannt](https://github.com/MiRo1310/ioBroker.telegram-menu/assets/38273154/d00ce491-9c60-4412-a747-87d40e10cb9d)

![Unbenannt1](https://github.com/MiRo1310/ioBroker.telegram-menu/assets/38273154/659910d4-5679-4173-83b0-97366ad4e104)

![Unbenannt2](https://github.com/MiRo1310/ioBroker.telegram-menu/assets/38273154/c64c12e8-884c-4fd2-ae78-462f1668ce2e)

**Comment by quorle** [comment]
Gerade nochmal getestet. Ist bei dem ganzen Menü so. Also liegt es scheinbar am Admin Adapter.

**Comment by MiRo1310** [comment]
Wechsle dich mal die Admin Version und schaue nach ob das Problem immer noch da ist. Ist aber schon komisch das es eine gewisse Zeit funktioniert

**Comment by quorle** [comment]
Ich habe gestern mal verschiedene Admin-Adapter Versionen versucht, jedoch bleibt das Problem bestehen. 
Was ich mir noch vorstellen könnte ist die JS-Version selbst. 
konntest du es mit einem aktuellen Beta-ioBroker nachstellen?

**Comment by MiRo1310** [comment]
Ich schaue da nachher noch mal rein

**Comment by MiRo1310** [comment]
Wann tritt dieser Fehler denn auf? Bei welcher Funktion?

**Comment by quorle** [comment]
Dieser Fehler tritt immer nach einer gewissen zweit auf. Ich kann die Zeit leider nicht einschätzen. Aber es ist bei jedem Menüpunkt so. 

Folgende Meldung kommt noch ab und zu unten links am Bildschirmrand:

![IMG_1153](https://github.com/MiRo1310/ioBroker.telegram-menu/assets/38273154/e4b58531-894d-4c6e-8386-241d33836c29)

Admin Version ist die letzte unstable.

**Comment by MiRo1310** [comment]
Nur komisch das es nur bei dir auftritt. Der Adapter ist über 700 mal installiert. Ich habe da absolut keine Idee zu. Und im Adapter ist auch nichts getimet so das es erst nach kurzer Zeit auftritt. Gibt es evtl ein Menü welches das evtl erst zu eskalieren bringt ?

**Comment by quorle** [comment]
Naja ich nutze keinen Adapter als Stable, da ich neue Funktionen gerne mit testen möchte. 

Ich kann dir eventuell am Sonntag einmal meine json config vom Adapter schicken. Hättest du hier eine email Adresse? Möchte es ungern hier öffentlich machen.

**Comment by MiRo1310** [comment]
Einfach an michael.roling@gmx.de

**Comment by MiRo1310** [comment]
Auf den ersten Blick kann ich nichts finden. Musst du einfach mal beobachten ob es eventuell an einem bestimmten Wert liegt. Aber eigentlich müsste dann auch ein Fehler im log kommen.

**Comment by MiRo1310** [comment]
Biste schon weiter gekommen?

**Comment by quorle** [comment]
Leider nein, das Problem besteht seit dem letzten Controller Update. Am 06.04.24 um 20:17 schrieb MiRo1310
                
            
            
                
                    Von: "MiRo1310" ***@***.***>Datum: 6. April 2024An: "MiRo1310/ioBroker.telegram-menu" ***@***.***>Cc: "quorle" ***@***.***>,"Author" ***@***.***>Betreff: Re: [MiRo1310/ioBroker.telegram-menu] Seit gestern Geht nichts mehr.  (Issue #122)
                
                
Biste schon weiter gekommen?

**Comment by MiRo1310** [comment]
Ich habe eine neue Version erstellt, vielleicht kannst du damit noch mal testen ob das einen Unterschied macht 1.7.0

**Comment by MiRo1310** [comment]
Jetzt läuft die neue Version, einfach mal probieren

**Comment by quorle** [comment]
Habe ich gerade installiert. Und teste es ein paar Tage lang.

**Comment by MiRo1310** [comment]
Läuft bisher alles?

**Comment by quorle** [comment]
Leider nein. Problem bleibt das gleiche. 
Man müsste mal ein System aufsetzen und dann den js-Controller nicht im stable zu betreiben. Da es nicht am Admin Adapter liegt, muss es ja dann am js-Controller liegen. 

Oder soll ich dir den Fehlercode nochmals hier her kopieren?

**Comment by MiRo1310** [comment]
Ja kopiere den noch mal nach hier

**Comment by quorle** [comment]
`<head></head>
telegram-menu.0 | 2024-05-26 14:28:09.428 | error | "TypeError: Cannot read properties of undefined (reading '🚿 Heizstab Status')\n at processData (/opt/iobroker/node_modules/iobroker.telegram-menu/build/src/lib/backend/processData.js:106:21)\n at checkEveryMenuForData (/opt/iobroker/node_modules/iobroker.telegram-menu/build/src/lib/backend/processData.js:51:19)\n at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n at async TelegramMenu.<anonymous> (/opt/iobroker/node_modules/iobroker.telegram-menu/build/src/main.js:222:55)"
-- | -- | -- | --
telegram-menu.0 | 2024-05-26 14:28:09.428 | error | "TypeError: Cannot read properties of undefined (reading '🚿 Heizstab Status')\n at processData (/opt/iobroker/node_modules/iobroker.telegram-menu/build/src/lib/backend/processData.js:106:21)\n at checkEveryMenuForData (/opt/iobroker/node_modules/iobroker.telegram-menu/build/src/lib/backend/processData.js:51:19)\n at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n at async TelegramMenu.<anonymous> (/opt/iobroker/node_modules/iobroker.telegram-menu/build/src/main.js:222:55)"
telegram-menu.0 | 2024-05-26 14:28:09.428 | error | Error processData: "Cannot read properties of undefined (reading '🚿 Heizstab Status')"
telegram-menu.0 | 2024-05-26 14:28:09.427 | error | Error processData: "Cannot read properties of undefined (reading '🚿 Heizstab Status')"
telegram-menu.0 | 2024-05-26 14:28:09.427 | error | Error processData: "Cannot read properties of undefined (reading '🚿 Heizstab Status')"
telegram-menu.0 | 2024-05-26 14:28:09.427 | error | "TypeError: Cannot read properties of undefined (reading '🚿 Heizstab Status')\n at processData (/opt/iobroker/node_modules/iobroker.telegram-menu/build/src/lib/backend/processData.js:106:21)\n at checkEveryMenuForData (/opt/iobroker/node_modules/iobroker.telegram-menu/build/src/lib/backend/processData.js:51:19)\n at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n at async TelegramMenu.<anonymous> (/opt/iobroker/node_modules/iobroker.telegram-menu/build/src/main.js:222:55)"
telegram-menu.0 | 2024-05-26 14:28:09.427 | error | "TypeError: Cannot read properties of undefined (reading '🚿 Heizstab Status')\n at processData (/opt/iobroker/node_modules/iobroker.telegram-menu/build/src/lib/backend/processData.js:106:21)\n at checkEveryMenuForData (/opt/iobroker/node_modules/iobroker.telegram-menu/build/src/lib/backend/processData.js:51:19)\n at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n at async TelegramMenu.<anonymous> (/opt/iobroker/node_modules/iobroker.telegram-menu/build/src/main.js:222:55)"
telegram-menu.0 | 2024-05-26 14:28:09.426 | error | "TypeError: Cannot read properties of undefined (reading '🚿 Heizstab Status')\n at processData (/opt/iobroker/node_modules/iobroker.telegram-menu/build/src/lib/backend/processData.js:106:21)\n at checkEveryMenuForData (/opt/iobroker/node_modules/iobroker.telegram-menu/build/src/lib/backend/processData.js:51:19)\n at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n at async TelegramMenu.<anonymous> (/opt/iobroker/node_modules/iobroker.telegram-menu/build/src/main.js:222:55)"
telegram-menu.0 | 2024-05-26 14:28:09.426 | error | "TypeError: Cannot read properties of undefined (reading '🚿 Heizstab Status')\n at processData (/opt/iobroker/node_modules/iobroker.telegram-menu/build/src/lib/backend/processData.js:106:21)\n at checkEveryMenuForData (/opt/iobroker/node_modules/iobroker.telegram-menu/build/src/lib/backend/processData.js:51:19)\n at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n at async TelegramMenu.<anonymous> (/opt/iobroker/node_modules/iobroker.telegram-menu/build/src/main.js:222:55)"
telegram-menu.0 | 2024-05-26 14:28:09.426 | error | Error processData: "Cannot read properties of undefined (reading '🚿 Heizstab Status')"
telegram-menu.0 | 2024-05-26 14:28:09.426 | error | Error processData: "Cannot read properties of undefined (reading '🚿 Heizstab Status')"
telegram-menu.0 | 2024-05-26 14:28:09.425 | error | Error processData: "Cannot read properties of undefined (reading '🚿 Heizstab Status')"
telegram-menu.0 | 2024-05-26 14:28:09.425 | error | "TypeError: Cannot read properties of undefined (reading '🚿 Heizstab Status')\n at processData (/opt/iobroker/node_modules/iobroker.telegram-menu/build/src/lib/backend/processData.js:106:21)\n at checkEveryMenuForData (/opt/iobroker/node_modules/iobroker.telegram-menu/build/src/lib/backend/processData.js:51:19)\n at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n at async TelegramMenu.<anonymous> (/opt/iobroker/node_modules/iobroker.telegram-menu/build/src/main.js:222:55)"
telegram-menu.0 | 2024-05-26 14:28:09.424 | error | "TypeError: Cannot read properties of undefined (reading '🚿 Heizstab Status')\n at processData (/opt/iobroker/node_modules/iobroker.telegram-menu/build/src/lib/backend/processData.js:106:21)\n at checkEveryMenuForData (/opt/iobroker/node_modules/iobroker.telegram-menu/build/src/lib/backend/processData.js:51:19)\n at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n at async TelegramMenu.<anonymous> (/opt/iobroker/node_modules/iobroker.telegram-menu/build/src/main.js:222:55)"
telegram-menu.0 | 2024-05-26 14:28:09.424 | error | "TypeError: Cannot read properties of undefined (reading '🚿 Heizstab Status')\n at processData (/opt/iobroker/node_modules/iobroker.telegram-menu/build/src/lib/backend/processData.js:106:21)\n at checkEveryMenuForData (/opt/iobroker/node_modules/iobroker.telegram-menu/build/src/lib/backend/processData.js:51:19)\n at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n at async TelegramMenu.<anonymous> (/opt/iobroker/node_modules/iobroker.telegram-menu/build/src/main.js:222:55)"
telegram-menu.0 | 2024-05-26 14:28:09.424 | error | Error processData: "Cannot read properties of undefined (reading '🚿 Heizstab Status')"
telegram-menu.0 | 2024-05-26 14:28:09.424 | error | Error processData: "Cannot read properties of undefined (reading '🚿 Heizstab Status')"
telegram-menu.0 | 2024-05-26 14:28:09.424 | error | Error processData: "Cannot read properties of undefined (reading '🚿 Heizstab Status')"
telegram-menu.0 | 2024-05-26 14:28:09.423 | error | Error processData: "Cannot read properties of undefined (reading '🚿 Heizstab Status')"
telegram-menu.0 | 2024-05-26 14:28:09.423 | error | Error processData: "Cannot read properties of undefined (reading '🚿 Heizstab Status')"
telegram-menu.0 | 2024-05-26 14:28:09.423 | error | "TypeError: Cannot read properties of undefined (reading '🚿 Heizstab Status')\n at processData (/opt/iobroker/node_modules/iobroker.telegram-menu/build/src/lib/backend/processData.js:106:21)\n at checkEveryMenuForData (/opt/iobroker/node_modules/iobroker.telegram-menu/build/src/lib/backend/processData.js:51:19)\n at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n at async TelegramMenu.<anonymous> (/opt/iobroker/node_modules/iobroker.telegram-menu/build/src/main.js:222:55)"
telegram-menu.0 | 2024-05-26 14:28:09.423 | error | "TypeError: Cannot read properties of undefined (reading '🚿 Heizstab Status')\n at processData (/opt/iobroker/node_modules/iobroker.telegram-menu/build/src/lib/backend/processData.js:106:21)\n at checkEveryMenuForData (/opt/iobroker/node_modules/iobroker.telegram-menu/build/src/lib/backend/processData.js:51:19)\n at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n at async TelegramMenu.<anonymous> (/opt/iobroker/node_modules/iobroker.telegram-menu/build/src/main.js:222:55)"
telegram-menu.0 | 2024-05-26 14:28:09.422 | error | "TypeError: Cannot read properties of undefined (reading '🚿 Heizstab Status')\n at processData (/opt/iobroker/node_modules/iobroker.telegram-menu/build/src/lib/backend/processData.js:106:21)\n at checkEveryMenuForData (/opt/iobroker/node_modules/iobroker.telegram-menu/build/src/lib/backend/processData.js:51:19)\n at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n at async TelegramMenu.<anonymous> (/opt/iobroker/node_modules/iobroker.telegram-menu/build/src/main.js:222:55)"
telegram-menu.0 | 2024-05-26 14:28:09.422 | error | "TypeError: Cannot read properties of undefined (reading '🚿 Heizstab Status')\n at processData (/opt/iobroker/node_modules/iobroker.telegram-menu/build/src/lib/backend/processData.js:106:21)\n at checkEveryMenuForData (/opt/iobroker/node_modules/iobroker.telegram-menu/build/src/lib/backend/processData.js:51:19)\n at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n at async TelegramMenu.<anonymous> (/opt/iobroker/node_modules/iobroker.telegram-menu/build/src/main.js:222:55)"
telegram-menu.0 | 2024-05-26 14:28:09.422 | error | Error processData: "Cannot read properties of undefined (reading '🚿 Heizstab Status')"
telegram-menu.0 | 2024-05-26 14:28:09.422 | error | Error processData: "Cannot read properties of undefined (reading '🚿 Heizstab Status')"
telegram-menu.0 | 2024-05-26 14:28:09.421 | error | "TypeError: Cannot read properties of undefined (reading '🚿 Heizstab Status')\n at processData (/opt/iobroker/node_modules/iobroker.telegram-menu/build/src/lib/backend/processData.js:106:21)\n at checkEveryMenuForData (/opt/iobroker/node_modules/iobroker.telegram-menu/build/src/lib/backend/processData.js:51:19)\n at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n at async TelegramMenu.<anonymous> (/opt/iobroker/node_modules/iobroker.telegram-menu/build/src/main.js:222:55)"
telegram-menu.0 | 2024-05-26 14:28:09.421 | error | Error processData: "Cannot read properties of undefined (reading '🚿 Heizstab Status')"
telegram-menu.0 | 2024-05-26 14:28:09.421 | error | "TypeError: Cannot read properties of undefined (reading '🚿 Heizstab Status')\n at processData (/opt/iobroker/node_modules/iobroker.telegram-menu/build/src/lib/backend/processData.js:106:21)\n at checkEveryMenuForData (/opt/iobroker/node_modules/iobroker.telegram-menu/build/src/lib/backend/processData.js:51:19)\n at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n at async TelegramMenu.<anonymous> (/opt/iobroker/node_modules/iobroker.telegram-menu/build/src/main.js:222:55)"
telegram-menu.0 | 2024-05-26 14:28:09.421 | error | Error processData: "Cannot read properties of undefined (reading '🚿 Heizstab Status')"
telegram-menu.0 | 2024-05-26 14:28:09.421 | error | "TypeError: Cannot read properties of undefined (reading '🚿 Heizstab Status')\n at processData (/opt/iobroker/node_modules/iobroker.telegram-menu/build/src/lib/backend/processData.js:106:21)\n at checkEveryMenuForData (/opt/iobroker/node_modules/iobroker.telegram-menu/build/src/lib/backend/processData.js:51:19)\n at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n at async TelegramMenu.<anonymous> (/opt/iobroker/node_modules/iobroker.telegram-menu/build/src/main.js:222:55)"
telegram-menu.0 | 2024-05-26 14:28:09.420 | error | Error processData: "Cannot read properties of undefined (reading '🚿 Heizstab Status')"
telegram-menu.0 | 2024-05-26 14:28:09.420 | error | "TypeError: Cannot read properties of undefined (reading '🚿 Heizstab Status')\n at processData (/opt/iobroker/node_modules/iobroker.telegram-menu/build/src/lib/backend/processData.js:106:21)\n at checkEveryMenuForData (/opt/iobroker/node_modules/iobroker.telegram-menu/build/src/lib/backend/processData.js:51:19)\n at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n at async TelegramMenu.<anonymous> (/opt/iobroker/node_modules/iobroker.telegram-menu/build/src/main.js:222:55)"
telegram-menu.0 | 2024-05-26 14:28:09.420 | error | Error processData: "Cannot read properties of undefined (reading '🚿 Heizstab Status')"
telegram-menu.0 | 2024-05-26 14:28:09.419 | error | "TypeError: Cannot read properties of undefined (reading '🚿 Heizstab Status')\n at processData (/opt/iobroker/node_modules/iobroker.telegram-menu/build/src/lib/backend/processData.js:106:21)\n at checkEveryMenuForData (/opt/iobroker/node_modules/iobroker.telegram-menu/build/src/lib/backend/processData.js:51:19)\n at TelegramMenu.<anonymous> (/opt/iobroker/node_modules/iobroker.telegram-menu/build/src/main.js:222:61)\n at TelegramMenu.emit (node:events:517:28)\n at Immediate._onImmediate (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:8493:53)\n at process.processImmediate (node:internal/timers:476:21)"
telegram-menu.0 | 2024-05-26 14:28:09.419 | error | Error processData: "Cannot read properties of undefined (reading '🚿 Heizstab Status')"

`

**Comment by MiRo1310** [comment]
Ich schaue mir das noch mal an. Hast du mal versucht Heizstab Status zu löschen, bzw. was steht in Heizstab Status drin? Evtl. ist der Wert nicht definiert und dadurch kommt dann der Error

**Comment by quorle** [comment]
Das Phänomen tritt bei all meinen Schaltflächen auf. Ich kann mal eine Fläche löschen und neu erstellen. Aber das ganze Menü ist leider sehr komplex aufgebaut 🙈

**Comment by MiRo1310** [comment]
Ich baue da noch gerade etwas ein was uns das helfen könnte ein zu grenzen

**Comment by MiRo1310** [comment]
at TelegramMenu.emit (node:events:517:28)\n at Immediate._onImmediate (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:8493:53)\n at process.processImmediate (node:internal/timers:476:21)" aber ich glaube das es wirklich vom js-controller kommt, da warst du aber auch mal auf Stable gegangen?

**Comment by MiRo1310** [comment]
@quorle  Besteht der Fehler immer noch?

**Comment by quorle** [comment]
@MiRo1310 
Ich teste noch. Bislang funktioniert es wieder. 

Nur der „zurück“ Button nicht. Diesen habe ich aber schon gelöscht und neu erzeugt.

**Comment by MiRo1310** [comment]
Dann schließe ich das hier erstmal, ansonsten kannst du es ja wieder öffnen

**Comment by quorle** [comment]
Muss das Ticket leider wieder eröffnen. 
bislang funktioniert alles, aber nun tritt das selbe Problem mit „Zurück“ (Menu:back) auf.

**Comment by MiRo1310** [comment]
Haste aber nicht. 😂
Ich glaube auch nicht das es was mit meinem Adapter zu tun hat, denn dann hätten das noch viel mehr Leute. Und warum sollte das auch so sein? Der Code ändert sich nicht. Ich kann es leider nicht nachvollziehen. Aber bitte poste noch mal die Logs die du bekommst, dann versuche ich noch mal ob ich was finden kann. Ich eröffne es dann mal wieder.

**Comment by quorle** [comment]
Hatte gestern mal Zeit mich um meinen ioB zu kümmern. Dabei habe ich den Telegram-Menü Adapter deinstalliert und wieder neu installiert. Config-Datei hochgeladen und seitdem läuft der Adapter ohne aussetzer.
