### ISSUE TITLE
Text in Parse-Mode funktioniert nicht

### ISSUE THREAD

**Issue by kilasat** [MiRo1310/ioBroker.telegram-menu#130]
![image](https://github.com/MiRo1310/ioBroker.telegram-menu/assets/42370557/686dad40-d107-47f7-a5b7-5df006b1e389)

hier die Ausgabe.

![image](https://github.com/MiRo1310/ioBroker.telegram-menu/assets/42370557/6dda66f2-c49a-4195-b154-3f6aaab46652)

**Comment by MiRo1310** [comment]
Zeig mal die komplette Eingabe

**Comment by MiRo1310** [comment]
Ja genau. Du musst oben den parse Mode anhaken

**Comment by kilasat** [comment]
Danke - Problem gelöst.
