### ISSUE TITLE
update 1.6.3 nix geht mehr

### ISSUE THREAD

**Issue by robschii** [MiRo1310/ioBroker.telegram-menu#138]
nach dem update von 1.5.x auf 1.6.3 erscheint im adapter nur noch 404 index_m.html nicht gefunden.

ein downgrade bringt auch nix, er sagt immer 1.6.3 wäre installiert. 

adapter gelöscht neu installiert, jetzt taucht er nach der instalation unter instanzen gar nicht mehr auf.

need help

**Comment by robschii** [comment]
im telegram selber sehe ich meine erste seite aber ohne funktion. als wäre auf dem server noch ein rest nach der deinstallation

**Comment by MiRo1310** [comment]
Bei einigen Usern läuft der RAM bei der Installation voll. Woran das liegt weiß ich nicht. Es gibt dazu ein Issue beim js Controller. Ich schaue am Wochenende nochmal ob ich was finden kann.

**Comment by robschii** [comment]
Okay, da.ich mich jetzt nicht so gut auskenne damit..woran sehe ich das und kann ich ggf etwas anderes an logs beisteuern?

**Comment by MiRo1310** [comment]
Ich habe leider noch keine neuen Infos.  Was kommt denn im log bei der Installation? Vielleicht auch einfach mal probieren über das Terminal zu installieren.

**Comment by MiRo1310** [comment]
Bitte einmal versuchen ob es mit der Version 1.7.0 wieder geht

**Comment by MiRo1310** [comment]
Jetzt läuft die neue Version, einfach mal versuchen

**Comment by MiRo1310** [comment]
@robschii Hast du die neuste Version schon mal getestet?

**Comment by MiRo1310** [comment]
Ich schließe das jetzt erstmal, kann ja gegebenenfalls wieder geöffnet werden
