### ISSUE TITLE
Object telegram-menu.0.navigation is invalid: Default value has to be stringified but received type "object"

### ISSUE THREAD

**Issue by Negalein** [MiRo1310/ioBroker.telegram-menu#14]
V 0.0.6

`telegram-menu.0 2023-04-20 10:54:50.292	warn	This object will not be created in future versions. Please report this to the developer.
telegram-menu.0 2023-04-20 10:54:50.291	warn	Object telegram-menu.0.navigation is invalid: Default value has to be stringified but received type "object"`

**Comment by MiRo1310** [comment]
Einmal von Github neu installieren
