### ISSUE TITLE
Wert einer SetState Aktion beeinflussen?

### ISSUE THREAD

**Issue by robert-ke** [MiRo1310/ioBroker.telegram-menu#144]
Hallo,

ist es möglich, den Wert, der in ein Objekt (Zeichenkette) geschrieben wird, zu beeinflussen?

Hier ein Beispiel:
![image](https://github.com/MiRo1310/ioBroker.telegram-menu/assets/74955542/04fec521-2859-4209-8559-8648b70070a8)

Ich möchte den Trigger R0 (Rollo Instanz 0 auf meiner SPS) mit den Werten im Objekt 0_userdata.0.Test mit folgendem Text haben:
Rollo0=Wert

Ich werte nur dieses eine Objekt aus und das wird zur SPS geschickt. Ich benötige einen Text der jeweiligen Instanz vorher und dann den Wert 0-100%.

Im Beispiel kommt aber nicht Rollo0=50 sondern nur 50:
![image](https://github.com/MiRo1310/ioBroker.telegram-menu/assets/74955542/d70d0774-d5b9-486a-87a6-02351f464a4c)

Gibts diese Möglichkeit und wenn ja, wie muss die Eingabe im SetState Wert erfolgen?

Vielen Dank

**Comment by MiRo1310** [comment]
Wenn ich das richtig verstehe, möchtest du einen Button haben der aus deinem vordefinierten Text Rollo0= und dem Wert in dem datenpunkt sendet. 

Nein das geht nicht. 
Zum Verständnis, warum kannst du nicht fest definierte Button erstellen die direkt die Werte wie Rollo0=50 usw. hat?

**Comment by MiRo1310** [comment]
Du hättest das nicht schließen müssen. Ich bin immer gerne bereit das zu erweitern.

**Comment by MiRo1310** [comment]
![image](https://github.com/MiRo1310/ioBroker.telegram-menu/assets/68854794/606164c8-81d9-4894-abb2-17eda3d57600)
Hi, anbei ein Screenshot wie es funktioniert, bitte einmal von Github laden und testen und dann ein Feedback da lassen. Bei Fragen gerne melden.

**Comment by MiRo1310** [comment]
Achso Test ist in dem Fall der feste Wert den du haben möchtest. Alles in den Klammer incl der klammer wird durch den Wert der id ersetzt. Wenn aber noch ein fester Wert hinter die klammern muss, das müsste ich noch anpassen.

**Comment by robert-ke** [comment]
Hallo, erstmal super, dass das doch umgesetzt wird. Ich habe Version 1.7.0 drauf - und die Aktion wie folgt angelegt:

![image](https://github.com/MiRo1310/ioBroker.telegram-menu/assets/74955542/2dcb139f-7e39-43fd-a5d9-b6fe6965e284)

Aber ich habe immer nur den Wert ohne Rollo0= im Objekt stehen:
![image](https://github.com/MiRo1310/ioBroker.telegram-menu/assets/74955542/d0d902f2-e28c-4fe9-bbfb-78b60d41f687)

Oder hab ich was falsch verstanden?

**Comment by MiRo1310** [comment]
Wenn du über die Katze installiert hast, sollte das funktionieren. Die Eingabe scheint richtig zu sein. Komisch das es nicht funktioniert. Du liest und schreibst zwar in den gleichen datenpunkt, aber das dürfte nicht das Problem sein. Ich schaue mir das morgen noch mal an.

**Comment by MiRo1310** [comment]
@robert-ke Ich habe noch ein paar fixes gemacht, aber es hatte auch davor bei mir funktioniert, bitte einmal testen. Also direkt noch mal über die Katze herunterladen

**Comment by robert-ke** [comment]
@MiRo1310 Vielen Dank - mit der Katze wie gewohnt aktualisiert, leider ohne Veränderung. Fehler hat er keinen geworfen, Version 1.7.0 siehe Screenshot:

![image](https://github.com/MiRo1310/ioBroker.telegram-menu/assets/74955542/2ea9a28a-1b23-4303-9a9f-e53cb508aa6f)

Hier ein Auszug aus dem Log, wo er auch Value to set: "60" setzt für die gedrückten 60%
![image](https://github.com/MiRo1310/ioBroker.telegram-menu/assets/74955542/d372a7ba-a557-485d-8de7-7015a9627c7f)

Hast noch eine Idee? Soll ich den Adapter mal vorsichtshalber löschen und nochmal neu installieren falls ggfs. mit dem Update was nicht klappt?

**Comment by MiRo1310** [comment]
Ich werde das morgen noch mal in meinem Produktiv System prüfen. Melde mich dann noch mal

**Comment by MiRo1310** [comment]
@robert-ke Ich habe es jetzt kurz auf mein produktiv System installiert, erst ging es nicht, der Fehler war, das der Zieldatenpunkt vom typ number war. ich habe diesen geändert auf string, danach funktioniert das ganze. Ich habe auch zusätzlich noch ein paar debug  logs eingebaut

**Comment by robert-ke** [comment]
@MiRo1310 , es tut mir leid, aber es tut nicht. Sehr hartnäckig. Ich hab den Adapter gelöscht und nochmal neu installiert, ohne Veränderung. Er schreibt nach wie vor nur den reinen Wert weg. Das Zielobjekt ist natürlich ein String:

![image](https://github.com/MiRo1310/ioBroker.telegram-menu/assets/74955542/9885a0e7-5777-448b-b489-8332d4ad2311)

Einstellung der Aktion wie gehabt:
![image](https://github.com/MiRo1310/ioBroker.telegram-menu/assets/74955542/18b8b7de-7b26-4e1c-9087-9071be121921)

**Comment by MiRo1310** [comment]
Ah. Ich habe den Fehler gefunden. Du nutzt dazu ein Submenu. Dann kann es auch nicht funktionieren. Schaue ich mir an

**Comment by robert-ke** [comment]
Ja, ich hab quasi ein Menü Rollos, von dort baue ich dann das Menü für die einzelnen Räume auf. Klickt man dann auf Wohnzimmer, kommt die 0-100% Anzeige. So wär das dann chronologisch für alle Räume angedacht.

Danke!

**Comment by MiRo1310** [comment]
Weiter gehts, jetzt sollte es aber klappen. Um ein Submenu Value zu ändern, einfach deinen statischen Text setzen wie gehabt und da wo das value hin soll anstatt das mit der Id zu machen einfach Rollo0={value}. Ich hoffe ich habe das richtig verstanden bzw um gesetzt, ansonsten bitte melden.

**Comment by robert-ke** [comment]
@MiRo1310 perfekt, jetzt hats geklappt:
![image](https://github.com/MiRo1310/ioBroker.telegram-menu/assets/74955542/9e3e1bab-b061-4452-9583-14ee763794ef)

Aktion wie folgt:
![image](https://github.com/MiRo1310/ioBroker.telegram-menu/assets/74955542/56cbec08-0249-44f2-948e-f807c19c09d5)

.. und schon läufts, das erleichtert mir für 20 Rollos sehr viel Arbeit. Vielen Dank für die tolle Erweiterung
