### ISSUE TITLE
The State .info.connection was not found!

### ISSUE THREAD

**Issue by Negalein** [MiRo1310/ioBroker.telegram-menu#15]
v 0.0.6

`telegram-menu.0 2023-04-20 10:54:50.401	error	The State .info.connection was not found!
telegram-menu.0 2023-04-20 10:54:50.400	error	undefined
telegram-menu.0 2023-04-20 10:54:50.300	info	starting. Version 0.0.6 (non-npm: MiRo1310/ioBroker.telegram-menu#b833a6861c53426e0579af2b4ca2d4e5adcd7a1b) in /opt/iobroker/node_modules/iobroker.telegram-menu, node: v16.19.1, js-controller: 4.0.24`

**Comment by MiRo1310** [comment]
Schaue ich mir gleich mal an
