### ISSUE TITLE
Problem Telegram mit Menü Adapter

### ISSUE THREAD

**Issue by McR1983** [MiRo1310/ioBroker.telegram-menu#152]
(Sorry wollte im Forum posten aber da kommt ständig "forbidden" Warum auch immer....)

Hey, 

hab auch das Problem bei einem der zwei Menüadapter mit dem "Bad Gateway... und es ist total langsam..."

Bei dem anderen Adapter mit anderem Telegram Adapter läuft alles gut. Allerdings viel weniger Menü drin.

Im zugehörigen Telegram auf dem Handy steht dann z.B. : "Message ignored" nach keine Ahnung mehrern Minuten oder sogar viel länger  - Und das nur wenn ich im Menü mich bewegen will noch keine Aufgabe sende oder so...

Sonst kommt im Iobroker Log nur irgendwann mal zwischendurch "Bad Gateway"

<html><body>

telegram.0 | 2024-06-10 14:11:52.638 | error | Failed sending [chatId - xxx]: Error: ETELEGRAM: 504 Gateway Timeout
-- | -- | -- | --

</body>
</html>

Nichts geändert außer die Updates der Adapter Telegram v3.4.1 und Telegram Menü v1.7.0

Bin ratlos :-)

**Comment by mcreuter** [comment]
Dann habe ich noch eine Frage warum ich bei einem Adapter (der älteste) unter Get state Apfragen unter eine, Punkt machen kann bei dem neuern nicht. Dann löscht der die bereits eingefügten werte wenn ich auf das Plus drücke und macht keine neue Zeile?

![2024-06-10 12_46_08-instances - iobroker – Mozilla Firefox](https://github.com/MiRo1310/ioBroker.telegram-menu/assets/120659358/794ec28c-09a5-419c-b0bb-365b1af1701b)

**Comment by mcreuter** [comment]
Ok Thema 1 ist erledigt.
Habe es mit einem neuen Bot probiert ohne Passwort das ging sofort,
Keine Ahnung jetzt habe ich den alten auch ohne Passwort im Adapter Telegram genutzt und es geht wieder :-)
Schein also am Passort zu liegen, also ich konnte im Bot auch kein neues mehr vergeben?! Abgeschafft? 
Das war alles :-( 

Thema 2 ist noch offen

**Comment by MiRo1310** [comment]
Von Github direkt einmal installieren oder auf die vorletzte latest zurück gehen

**Comment by mcreuter** [comment]
Ok, aber warum geht das dann bei einem und beim anderen nicht? Was bringt dann ein zurück gehen?

**Comment by MiRo1310** [comment]
Weil in 1.7.0 ein Bug drin ist

**Comment by mcreuter** [comment]
ok das geht aber schon länger nicht, nicht erst seit 1.7.0... Was aber immer noch nicht erklärt warum das bei dem einen geht beim anderen nicht... Oder muss ich den komplett neu anlegen, wenn es wieder geht bzw ich zurück wechsle?

**Comment by MiRo1310** [comment]
Dann einmal von Github direkt über die Katze installieren. 

Was heißt das eine funktioniert und das andere nicht?

**Comment by mcreuter** [comment]
Hab ich oben die Fotos rein gemacht. Das erste Foto Adapter.0 das zweite Foto Adapter.1
Beim .0 gehts (ist älter schon), beim .1 gehts nicht, auch nicht nach dem npm install gerade

**Comment by MiRo1310** [comment]
Wie hast du den denn installiert?

**Comment by mcreuter** [comment]
vorhin unter terminal mit: npm i iobroker.telegram-menu

**Comment by MiRo1310** [comment]
auf die github katze ganz rechts

**Comment by mcreuter** [comment]
ja das meinte ich hatte ich zuerst gemacht... machs gerade nochmal sicherheitshalber

**Comment by mcreuter** [comment]
Noch eine Idee?

**Comment by MiRo1310** [comment]
Adapter Upload durchführen. Oder eventuell neu starten.

**Comment by MiRo1310** [comment]
Adapter evtl. Deinstallieren und neu installieren. Vorher aber ein Backup machen und die Einstellungen sichern

**Comment by mcreuter** [comment]
> Adapter Upload durchführen. Oder eventuell neu starten.

was meinst du mit upload?

**Comment by mcreuter** [comment]
> Adapter evtl. Deinstallieren und neu installieren. Vorher aber ein Backup machen und die Einstellungen sichern

Mache ich morgen :-)

**Comment by mcreuter** [comment]
???

**Comment by MiRo1310** [comment]
Sorry, Erstmal ein komplettes Backup machen. dann biste schon mal auf der sicheren Seite. 
![image](https://github.com/MiRo1310/ioBroker.telegram-menu/assets/68854794/72217fce-4ef1-41a2-956d-ef299117736d)
Darüber kannst du Einstellungen speichern und auch wieder importieren

**Comment by MiRo1310** [comment]
Hast du schon mal einen Adapter upload probiert? 
![image](https://github.com/MiRo1310/ioBroker.telegram-menu/assets/68854794/4d6e74f4-5697-4698-9416-2e1e31c2d100)

**Comment by mcreuter** [comment]
> Sorry, Erstmal ein komplettes Backup machen. dann biste schon mal auf der sicheren Seite. ![image](https://private-user-images.githubusercontent.com/68854794/339430695-72217fce-4ef1-41a2-956d-ef299117736d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyOTU4NzIsIm5iZiI6MTcxODI5NTU3MiwicGF0aCI6Ii82ODg1NDc5NC8zMzk0MzA2OTUtNzIyMTdmY2UtNGVmMS00MWEyLTk1NmQtZWYyOTkxMTc3MzZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEzVDE2MTkzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1MmM0YjJmN2VlYTM0YTUzNzNlNTVmZGE4YWU5NDhkOTdlYTk4OWI1MjZiZDVmMjYyZGMxM2ZiNDE1NTczMTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SxU4kfXBxZqDyWFcTOE_A8BYe15ytTRE0cceWg2Vw9g) Darüber kannst du Einstellungen speichern und auch wieder importieren

Hey, ja ne das geht eben auch nicht... Hatte ja den einen .1 glöscht und neu installiert und wollte das genauso machen, aber beim upload passiert nix!

**Comment by mcreuter** [comment]
> Hast du schon mal einen Adapter upload probiert? ![image](https://private-user-images.githubusercontent.com/68854794/339432051-4d6e74f4-5697-4698-9416-2e1e31c2d100.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyOTU4NzIsIm5iZiI6MTcxODI5NTU3MiwicGF0aCI6Ii82ODg1NDc5NC8zMzk0MzIwNTEtNGQ2ZTc0ZjQtNTY5Ny00Njk4LTk0MTYtMmUxZTMxYzJkMTAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEzVDE2MTkzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhZWM3YmE1Y2IxZDUwYTMxYmFjZDI5NTYxM2EzMDIxOTkzODViZmYzNTM2NTg4MTZkYzJmOGYyMzM1N2NhZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0GNFg9nRbbCuvjvqp5p6sVIh8IWzPjicBNsYf-2mxkM) Hier gibt es einen Button dazu

Ah ok nie gesehen weil ich nie in der Ansicht bin... lustig... naja aber wenn ich da auf den Button klicke passiert nix... 2 Browser probiert

**Comment by MiRo1310** [comment]
Was soll ich dir jetzt raten ausser neu installieren? Es ist immer sehr schwer zu sagen. Sicher doch mal die Daten erstelle eine neue Instanz vom adapter und versuche die daten da rein zu packen

**Comment by mcreuter** [comment]
> Was soll ich dir jetzt raten ausser neu installieren? Es ist immer sehr schwer zu sagen. Sicher doch mal die Daten erstelle eine neue Instanz vom adapter und versuche die daten da rein zu packen

JA aber nochmal hab eich ja bei einer Instanz gemacht, jetzt kriege ich das Bakup nicht wieder rein... Dann würde ich das ja für den ganzen Adapter machen.. aber wenn ich meine Menüs nicht rein bekomme?! Dann ist doch mist.... Deshalb hatt eich dich ja sogar gefragt ob man das manuell irgendwie wieder rein bekommt zur not....

**Comment by MiRo1310** [comment]
Man kann doch Daten exportieren und importieren. Das funktioniert auch nicht? Ich teste später noch mal

**Comment by mcreuter** [comment]
> Man kann doch Daten exportieren und importieren. Das funktioniert auch nicht? Ich teste später noch mal

JA genau export ja, import nein

**Comment by mcreuter** [comment]
Hab noch ne neue Instanz aus der 1.7.1 angelegt und auch da Datei importiert un nix passiert

**Comment by MiRo1310** [comment]
Ich weiß nicht ob ich das heute Abend noch schaffe.

**Comment by mcreuter** [comment]
> Ich weiß nicht ob ich das heute Abend noch schaffe.

Ok kein Thema... ist ja gut das du es sagst... Solange mein wichtigstes Menü noch läuft alles gut :-)

**Comment by MiRo1310** [comment]
Du hast recht das importieren funktioniert nicht, warum auch immer. Ich lege direkt mal ein Issue an

**Comment by MiRo1310** [comment]
Im Moment kann ich nichts tun, da das Problem nicht bei mir zu liegen scheint. Bin aber dran.

**Comment by mcreuter** [comment]
> Im Moment kann ich nichts tun, da das Problem nicht bei mir zu liegen scheint. Bin aber dran.

ok dann warte ich mal,  danke

**Comment by mcreuter** [comment]
Noch nix neues was import angeht?

**Comment by MiRo1310** [comment]
Auf mein Issue kam noch keine Reaktion, sorry.

**Comment by MiRo1310** [comment]
Ich habe heute eine Antwort bekommen, und habe nach langem Suchen den Fehler gefunden. Sobald das gefixt ist melde ich mich.

**Comment by MiRo1310** [comment]
So nun ist es endlich soweit , der Fehler wurde behoben. Jetzt solltest du wieder die Config laden können. Bitte einmal testen. Ich schliesse dieses Issue erstmal, bei weiteren Problemen gerne ein neues auf machen.
