### ISSUE TITLE
Bei einem neuen GetState können keine weiteren ID's angelegt werden

### ISSUE THREAD

**Issue by Willi-Wunder** [MiRo1310/ioBroker.telegram-menu#153]
Hallo Michael,

wollte gerade einen neuen GetState anlegen. Sobald ich auf das "Plus" Zeichen klicke um eine weitere ID anzulegen, wird die Zeile gelöscht.
Bei einem bereits bestehenden GetState erscheint eine neue Zeile und es können weitere ID's angelegt werden. 
Getestet im Firefox und Edge Browser, 2x keine Möglichkeit weitere Werte zu einem Trigger hinzuzufügen.
![Getstateer](https://github.com/MiRo1310/ioBroker.telegram-menu/assets/77007062/773a7d0d-f155-4717-9dd7-5c7e8ee35878)
![Getstateer2](https://github.com/MiRo1310/ioBroker.telegram-menu/assets/77007062/e21ebc35-83a6-4c52-9e8f-7301df0d4963)

**Comment by MiRo1310** [comment]
Das ist eigentlich behoben in 1.7.1, ich schaue aber noch mal nach

**Comment by MiRo1310** [comment]
Ist es doch wohl nicht. Ich bin dran

**Comment by Willi-Wunder** [comment]
Super, es können nun wieder mehrere ID's angelegt werden, Problem ist also behoben. 
Vielen Dank :-)
