### ISSUE TITLE
Importieren von Daten funktioniert nicht

### ISSUE THREAD

**Issue by MiRo1310** [MiRo1310/ioBroker.telegram-menu#154]

**Comment by MiRo1310** [comment]
https://github.com/ioBroker/adapter-react-v5/issues/350

**Comment by McR1983** [comment]
> [ioBroker/adapter-react-v5#350](https://github.com/ioBroker/adapter-react-v5/issues/350)

Hey @MiRo1310 gibt's schon Neuigkeiten wann der Import/export wieder geht?

**Comment by MiRo1310** [comment]
Nein leider nicht. Ich hatte heute Morgen noch mal geschaut, aber noch nichts neues gesehen.
