### ISSUE TITLE
Ein Wert wird bei Navigation nicht ausgeführt, die anderen aber schon

### ISSUE THREAD

**Issue by Willi-Wunder** [MiRo1310/ioBroker.telegram-menu#155]
Hallo Michael,
in der aktuellen Version wird ein Wert nicht ausgeführt. Ich kann meine Heizung/ Wasser mit dem Wert AUS(4) + Party(2) schalten. Der Wert EIN(0) wird aber nicht ausgeführt. Es kommt auch kein Fehler im Log.
Das steht hier bei Navigation:
![Heizung-Wasser](https://github.com/MiRo1310/ioBroker.telegram-menu/assets/77007062/823a3498-087a-4e68-ac90-9a7fa8f86a69)

Bei SetState steht dies:
![Heizung-Wasser_set](https://github.com/MiRo1310/ioBroker.telegram-menu/assets/77007062/1da3785a-e49f-4c8b-af67-3620343bac9b)

Woran könnte dies liegen, da er ja die anderen beiden Werte ausführt? Sehe gerade keinen Fehler im Menü. Was mir allerdings aufgefallen ist wenn ich auf EIN drücke, dass der Wert zwar nicht ausgeführt wird, aber der letzte Zustand dann nochmal geschickt wird.

**Comment by MiRo1310** [comment]
Das Problem habe ich gefunden, das war ein Fehler in der Abfrage ob eine Wert existiert , und wenn ich auf 0 abfrage kommt false raus. 😉

**Comment by MiRo1310** [comment]
Wenn es nicht funktioniert bitte das Ticket wieder öffnen
