### ISSUE TITLE
Werte aus erstellten Funktionen

### ISSUE THREAD

**Issue by thorsten1978** [MiRo1310/ioBroker.telegram-menu#159]
Wie funktioniert das genau ?
Ich nehme mal an in iobroker unter Aufzählungen unter Funktionen die Werte dort sind gemein ?
Muss man den iobroker erst neu starten damit das klappt ?
Ich bekomme keine Werte angezeigt, glaube irgenwas mache ich falsch....

Bei GetState unter 
ID: functions=weather
dann rechts den 
Text: Ergebnis für {common.name} ist && 

Da kommen aber keine Werte zurück, sondern nur der Text wie er da steht.

Werte aus erstellten Funktionen

    Um alle Werte der einstellbaren Funktionen zu bekommen, muss man anstatt der ID einfach functions=Licht z.B. schreiben.
    Wenn man im Ausgabe Text den Namen des Datenpunkts haben möchte trägt man einfach an der gewünschten Position im Text {common.name} ein

**Comment by MiRo1310** [comment]
Kannste mir mal genau zeigen was du definiert hast, damit ich das nachstellen kann.
