### ISSUE TITLE
State wird im Deconz Adapter zwar korrekt gesetzt, wirkt sich aber nicht aus...

### ISSUE THREAD

**Issue by Iceman808** [MiRo1310/ioBroker.telegram-menu#167]
Ich habe bis vor kurzem über das Telegram-Menu meine Zigbee Lampen über den Deconz Adapter geschaltet, in dem ich das Object On im geweiligen Schalter auf true oder false gesetzt habe. Dies habe ich über das SetState Menue gemacht:

![grafik](https://github.com/user-attachments/assets/0a6a0528-0a7f-4561-9d25-79a67fe6a1c9)

Seit einiger Zeit werden die Lampen aber nicht mehr geschaltet obwohl sich der State im Deconz Adapter entsprechend auf true/false stellt. 

Wenn ich das Object On im geweiligen Schalter manuell setzt werden auch die Lampen an/aus geschaltet, nur wenn dies über telegram-menü passiert ignorieren die Lampen dies. 

Ich habe mir jetzt darüber beholfen, das ich per Telegram-Menü einen user-data Werte setze und dieser per Blockly den Deconz Wert anpasst. Aber das kann es ja eigentlich nicht sein oder? 

Muss ich in einem SetState Einträgen etwas anpassen oder ist das ein Bug?

Der andere Weg (GetState) funktioniert korrekt.

IOBroker Version ist: 10.8.2 und betreibe den IOBroker als Docker Container.

-   Adapter version:  1.7.4
-   JS-Controller version: 8.3.1
-   Node version: v18.20.4
-   Operating system: docker (official image - v9.1.2) unter Ubuntu 22.04

**Comment by MiRo1310** [comment]
Nimm mal den Haken bei ack raus.

**Comment by Iceman808** [comment]
> Nimm mal den Haken bei ack raus.

Super, ja dann klappt es wieder. Danke für die schnelle Hilfe.
