### ISSUE TITLE
Zeitstempel Fehler

### ISSUE THREAD

**Issue by mickemup** [MiRo1310/ioBroker.telegram-menu#168]
**Describe the bug**  
Bei Benutzung von Zeitstempel erfolgte keine Ausgabe in Telegram und Errormeldungen gemäss Screenshot wurden erzeugt

**To Reproduce** 
Im Reiter Navigation unter Text: 
Text aus Helper Text genommen und mit ID ergänzt.
"meine Zeit: {time.ts,(DD MM YYYY hh:mm:ss:sss),id:'alias.0.myfolder.xyz'}"
Fehler im IoBroker gemäss Screenshot.
Keine Ausgabe in Telegram

**Expected behavior**  
Ausgabe des Zeitstempels According Dokumentation

**Screenshots & Logfiles**  
![TGM](https://github.com/user-attachments/assets/b73e4d77-31e6-4774-b467-4f81751f4450)

**Versions:**

-   Adapter version: 1.7.4
-   NPM: 9.6.7
-   Node.js: v18.17.1
-  iobroker js. :5.0.19
-   Operating system: linux (lx-container auf proxmox)

**Comment by MiRo1310** [comment]
Ich habe mir das gerade mal angeschaut, du hast da einen Fehler drin. Schau mal hier, du darfst die id nicht dahinter hängen, die kommt aus dem Feld Id selbst 
![image](https://github.com/user-attachments/assets/58a15999-553c-4f8f-aa65-483554c5b5f6)

**Comment by mickemup** [comment]
Ok aus dem helpertext wird nicht ganz klar, wo die ID denn hinmuss. Bin gerade unterwegs und kann nicht testen. Wo müsste denn die ID hin?
Evtl. müsste man den Helpertext etwas klarer formulieren. Ausser ich als DAU war der einzige der das nicht hinkriegt ;-)

**Comment by MiRo1310** [comment]
Bitte noch einmal testen
