### ISSUE TITLE
sind Räume möglich?

### ISSUE THREAD

**Issue by Negalein** [MiRo1310/ioBroker.telegram-menu#17]
ist es eventuell möglich, mit Räumen zu arbeiten?

Also zB
Wohnzimmer
   |___Licht
   |___Steckdose
   |___etc.

Küche
   |___Licht
   |___Steckdose
   |___etc.

usw.

**Comment by MiRo1310** [comment]
Nein ich glaube nicht, denn der Text der gesendet wird muss eindeutig sein. 
Wohnzimmer
|___ Wohnzimmer Licht
|___ Wohnzimmer Steckdose usw.

**Comment by Negalein** [comment]
> Nein ich glaube nicht, denn der Text der gesendet wird muss eindeutig sein.

hab hier was mit Blockly gefunden.
Vielleicht ist es implementierbar.

https://youtu.be/oPOxA8sTCxU

**Comment by Negalein** [comment]
> Was genau. Baut er etwas mit Räumen?

Ja, ab hier ca. zu sehn.
https://youtu.be/oPOxA8sTCxU?t=225

**Comment by MiRo1310** [comment]
Ich habe mir das Video mal angeschaut, ich kann aber nichts zu deinem Wunsch finden!

**Comment by Negalein** [comment]
> Ich habe mir das Video mal angeschaut, ich kann aber nichts zu deinem Wunsch finden!

Ok, sind jetzt nicht direkt "Räume", aber Prinzip bleibt gleich.

hier ist zB die Übersicht
![image](https://user-images.githubusercontent.com/45309436/235298935-3fe047ce-3c45-4953-8518-f5e198d6837a.png)

und hier die Unterpunkte von "Schaltungen"
![image](https://user-images.githubusercontent.com/45309436/235299614-5719503a-8e53-4800-8b81-3566e7f29719.png)

mit dem Button "Übersicht" kommt man wieder zum Hauptmenü

**Comment by MiRo1310** [comment]
ja aber das kannst du genau so im Adapter anlegen, nirgends hat er doppelte Buttons

**Comment by Negalein** [comment]
> ja aber das kannst du genau so im Adapter anlegen, nirgends hat er doppelte Buttons

Ok, wie schaut im Adapter die Konfig aus, wenn es zB so wie oben sein soll?
Das verstehe ich nicht.

**Comment by MiRo1310** [comment]
Morgen früh werde ich das mal bauen

**Comment by MiRo1310** [comment]
![grafik](https://user-images.githubusercontent.com/68854794/235342472-cfd4d9b0-63fb-47cd-8d9f-1b63a2ac7b05.png)

**Comment by Negalein** [comment]
> Ich weiss nicht ob wir an einander vorbei reden, aber das geht doch ohne Probleme

Danke, ich hab wohl zu kompliziert gedacht! 😀
