### ISSUE TITLE
duplicate actions, maybe even between menues

### ISSUE THREAD

**Issue by OneCreek** [MiRo1310/ioBroker.telegram-menu#175]
Is it possible to copy actions from a e.g. GetState and copy them to a e.g. SetState or different trigger GetState or even different menu?
Idea would be to not start for every user (different menu) or when setting up the action for a trigger from scratch. 

One idea would be 
1. again such a drop(box) or 
2. a switch to a text field instead of the table. There one could copy the plain info of the table as text and switch back to table format in the new action where one could paste it again.

**Comment by MiRo1310** [comment]
Muss ich mir anschauen, sicherlich möglich. Aber das wird etwas dauern bis ich dazu komme. Vielleicht hast du ja mal ein genaues Beispiel damit ich mir das besser vorstellen kann. 

Du kannst aber separate Menüs erstellen die für mehrere Benutzer gelten.

**Comment by OneCreek** [comment]
Ich habe für einen Nutzer folgende Action angelegt und wollte mir sparen, diese für den weiteren Nutzer (aufgrund insgesamt anderem Menüumfang) neu einzugeben:
![grafik](https://github.com/user-attachments/assets/497292b7-7df2-48cd-a98c-97e5a179a63b)

Ich konnte es dann über die allgemeine import/export Funktion nach https://github.com/MiRo1310/ioBroker.telegram-menu/releases/tag/v2.0.0 mit https://github.com/MiRo1310/ioBroker.telegram-menu/issues/154 https://github.com/MiRo1310/ioBroker.telegram-menu/issues/152 und entsprechendes Kopieren der Config in den zweiten User/Menü lösen. 

Falls die Konfiguration jedoch mal komplexer wird, wäre eine "punktuelle" import/export Funktion natürlich praktisch. 
Hier kommen mir 3 Möglichkeiten in den Sinn. 
1. wie bei deiner DropBox für das Menü an sich, nur eben auch für einzelne Aktionen über Menüs hinweg. 
![grafik](https://github.com/user-attachments/assets/d3674ef3-ad62-43fc-841b-6e83ba338981)
Am Rande: hier wäre vllt. noch ein Hinweis gut, bei "wählen sie ein Menü aus", ob es sich um das Quell oder Ziel Menü handelt. 
2. wie bei ioBroker in den Skrips mittels import/export
![grafik](https://github.com/user-attachments/assets/9a8b1574-1515-48f1-a7b8-fe6829a1fccf)
![grafik](https://github.com/user-attachments/assets/0e486fd3-35a0-48ec-a752-cd55dea7d128)
Das geht ja für einzelne Skript-Blöcke (wenn ausgewählt) oder einzelne komplette Skripte https://forum.iobroker.net/post/241955
Man exportiert einen Block oder Skript, kopiert die config dazu in die Zwischenablage und importiert sie anschließend wieder. 
3. wie bei [duplicati](https://github.com/duplicati/duplicati). hier gibt es die Option über auswählbare Optionen Einstellungen vorzunehmen, oder eben über "als Text bearbeiten", was im Endeffekt die Config dahinter ist. 
![grafik](https://github.com/user-attachments/assets/1ace8a21-589c-4e32-8db6-e08c2e27d05d)
oder eben über "als Text bearbeiten", was im Endeffekt die Config dahinter ist. 
![grafik](https://github.com/user-attachments/assets/009058c8-b924-42a7-95a2-8f3cb8af3e4b)
Man kann hier einfach hin und her wechseln. 
Dann kann man diesen Text in andere Sicherungsprofile wieder einfügen. Das wäre bei telegram-menu dann eben unter einem anderen Menü. 

Tatsächlich finde ich Option 2 sehr gut handhabbar, eine an Option 1 oder alternativ 3 wäre natürlich auch denkbar. 

Hoffe ich konnte ein wenig brauchbares Input liefern zu meinen Gedanken:)

**Comment by MiRo1310** [comment]
Ja ich werde mir das genauer anschauen

**Comment by MiRo1310** [comment]
Habe ich hinzugefügt, bitte testen
