### ISSUE TITLE
Wert-Feld Eigenschaften/Inhalt (insbesondere in Verbindung mit Switch-Option)

### ISSUE THREAD

**Issue by OneCreek** [MiRo1310/ioBroker.telegram-menu#181]
Beim Inhalt des Wert Feldes unter SetState ist mir nicht klar, wann wie in den Beispielen "" (kein Inhalt), " " (Leerzeichen), "-" (Bindestrich) oder "!" (Ausrufezeichen) verwendet werden kann, soll oder muss. 

Dabei ist mir aufgefallen, dass bei der aktivierten Option "Switch" das Feld leer sein kann, bei deaktiviertem Switch muss ein Inhalt/Zeichen eingegeben werden. 

Beim Verständnis von einem Switch, dass es eben nur true/false gibt, macht es Sinn, dass man keinen Wert übergeben/vorgeben muss. 
Falls man aber die Möglichkeit haben sollte, verschiedene Switch-States vorzugeben, wie z.B. auch on/off, würde es ggfls. wieder Sinn machen, hier einen Wert einzugeben - oder ist das [hiermit](https://github.com/MiRo1310/ioBroker.telegram-menu/blob/main/docs/de/README.md#-der-wert-des-status-ge%C3%A4ndert-werden) bereits festgelegt. Aber eingeben kann man es ja gerade - und auch leer lassen. 

Bei deaktivierter Switch-Option muss hingegen immer ein Zeichnen eingegeben werden. Egal ob "-" oder "!". Ein leer lassen wie bei aktivierter Switch-Option ist nicht möglich. Was ist der Gedanke hinter dieser Vorgabe?

Version 2.0.0 wird eingesetzt.

**Comment by MiRo1310** [comment]
Jetzt wird es so sein, das input Feld kann immer leer sein, wenn man Switch aktiviert wird das input Feld einfach deaktiviert
