### ISSUE TITLE
not possible to scroll entry lists

### ISSUE THREAD

**Issue by OneCreek** [MiRo1310/ioBroker.telegram-menu#203]
Telegram-menu: v2.1.3

Ich kann bei vielen Einträgen in der Navigation aber auch Aktion wie SetState oder GetState nicht scrollen.
Reproduzierbar in der aktuellen Version von Firefox 132.0.2 aber auch Microsoft Edge Version 131.0.2903.51.
workaround ist einfach im Browser raus zu zoomen...

![grafik](https://github.com/user-attachments/assets/a781f4cc-2d97-42ce-acd1-3409f70759ef)

**Comment by MiRo1310** [comment]
Bitte einmal testen ob das funktioniert, hier lokal in der Entwicklungsumgebung ging das. Ansonsten noch mal wieder eröffnen

**Comment by OneCreek** [comment]
ja, mit deinem Code, meinen bescheidenen Skills was css angeht und ein wenig googlen konnte ich scrollen :)

**Comment by MiRo1310** [comment]
Ich verstehe nicht ganz.

**Comment by OneCreek** [comment]
ich musste erst einmal schauen/probieren, wie ich die Änderungen in der Entwicklungsumgebung teste :D 
Aber hat funktioniert :)

**Comment by MiRo1310** [comment]
Ja man kann direkt von Github über einen link den mal über die Katze im iobroker einträgt, installieren

**Comment by OneCreek** [comment]
> Ja man kann direkt von Github über einen link den mal über die Katze im iobroker einträgt, installieren

Ja, https://github.com/MiRo1310/ioBroker.telegram-menu/tree/1d2f8e6 funktioniert. Gerade rausgefunden. Hat nur ewig gedauert zu laden.. :) Danke!
