### ISSUE TITLE
Keine Tastatur Eingabe möglich

### ISSUE THREAD

**Issue by JimmyBondi** [MiRo1310/ioBroker.telegram-menu#211]
Habe das Problem, dass ich an folgender Stelle nichts mehr bearbeiten kann.
Das kleine Fenster kann ich zwar größer ziehen, aber es werden keine Tastatur Eingaben angenommen.
Hab es auch mit einem anderen Browser ausprobiert und auch mit einem Adapter Update via Github.

js-controller: 7.03
Node.js: v20.18.1

![2024-12-01 10_10_01-instances - iobroker – Mozilla Firefox](https://github.com/user-attachments/assets/cffc31ab-fa84-48a6-96ed-c09332718db9)

**Comment by MiRo1310** [comment]
#212
