### ISSUE TITLE
Löschen von Einträgen nicht möglich

### ISSUE THREAD

**Issue by JimmyBondi** [MiRo1310/ioBroker.telegram-menu#220]
Ich versuche einen Eintrag über den roten Papierkorb Button zu löschen, was leider nicht möglich ist.
Es erscheint dabei keine Fehlermeldung oder ähnliches.

![Papierkorb](https://github.com/user-attachments/assets/d3c22391-5178-44f8-a2f5-e1d3e9663adc)

**Comment by MiRo1310** [comment]
Schaue ich mir an. Ich habe letztes einiges anscheinend kaputt gemacht als Ich typescript eingebaut habe. Sollte aber eine Kleinigkeit sein.
