### ISSUE TITLE
Rückmeldung an den Auslöser

### ISSUE THREAD

**Issue by raschy** [MiRo1310/ioBroker.telegram-menu#24]
Kein Bug, ein Wunsch zur Erweiterung:
Kann man noch Texte zur Rückmeldung hinterlegen nach dem Muster "Licht - Aktor1 eingeschaltet" ?

Wäre doch hilfreich, wenn eine Rückmeldung an den Auslöser der Schaltaktion gesendet würde.

**Comment by MiRo1310** [comment]
@raschy Ich würde das so machen, das man die Funktion aktivieren kann oder eben nicht nutzt. Zudem denke ich, sollte der User den gewünschten Text eingeben mit einem Platzhalter für den Wert.

**Comment by raschy** [comment]
Ja, so habe ich mir das gedacht. Aktivierbar durch den Benutzer - unbedingt. Auch den Text vom User einzustellen ist super. Hat aber keine Eile - ist ja ein Wunsch.

**Comment by MiRo1310** [comment]
So ich habe ein Update gemacht, bitte speichere aber erstmal deine daten als csv.
Ich bin mir nicht ganz sicher ob deine Daten noch gehen wenn du die neue Version installierst.

**Comment by raschy** [comment]
Soeben Update gemacht (weiterhin Version 0.0.8), vorher Daten Exportiert. In den neuen Adapter wollte ich dann die Daten wieder Importieren - keine Schaltflächen vorhanden. Die kommen erst, wenn ein Telegram-Teilnehmer eingetragen ist. Nach Import sieht es dann so aus:
![tg_menu_nachImport](https://user-images.githubusercontent.com/75622810/236637938-739aed01-eb91-47a9-b085-59d19e04a9e9.png)

**Comment by MiRo1310** [comment]
ging das denn ohne importieren nicht?

**Comment by raschy** [comment]
Ich wollte es mir einfach machen. Dachte, nach dem Hinweis auf 'speichern der Daten' wäre das eine gute Idee.
Ich hab es dann von Hand gemacht. Hier wird mir keine Auswahl für "Auslöser" angeboten. Also komme ich hier nicht weiter.

**Comment by MiRo1310** [comment]
du musst auf jeden fall speichern um die auslöser zu bekommen, und es darf auch nicht 2 mal der gleiche User da sein

**Comment by raschy** [comment]
Das nix doppelt da sein darf ist schon klar. Das doppelte hab ich rausgelöscht. Speichern geht nicht - nur schließen.
![tg_menu_setState](https://user-images.githubusercontent.com/75622810/236638597-2429a92a-2047-4553-a1a6-2d94d5bd031c.png)

**Comment by MiRo1310** [comment]
ich meine in der navigation, die einfach um ein leerzeichen erweitern das du speichern kannst, dann werden die auslöser generiert

**Comment by raschy** [comment]
Das hab ich jetzt hinbekommen. Ich hab jetzt einen Datenpunkt, den ich toggeln will - klappt nicht. Die Rückmeldung (true/false) funktioniert, wenn ich den Datenpunkt manuell geändert habe. Den Text, den ich eingegeben habe wird nicht übermittelt. Ist der irgendwo gecacht?

**Comment by MiRo1310** [comment]
Leider muss ich zu meinem bedauern sagen, das es bei mir im meinem Hauptsystem läuft

**Comment by raschy** [comment]
Das glaub ich dir gerne. Ich habe jetzt mit Auslöser 'Steckdose' einen zweiten booleschen Datenpunkt eingebunden. Der toggelt wie gewünscht. Der andere mit 'Licht' macht nichts, ausser den Status des Datenpunkts richtig zurückgeben. Ich habe den Text und die Bestätigung rausgenommen - kommt aber weiterhin. Muss noch irgendwo gecacht sein. Bin auch etwas ratlos.

**Comment by MiRo1310** [comment]
ich schaue mir das nochmals an, aber das ist so gebaut das der wert nur einmal geschickt werden kann.
der datenpunkt der toggelt, kommt denn da der String wie gewünscht?

**Comment by raschy** [comment]
Ich hab das dann nochmal schrittchen für schrittchen gemacht. Erst toggeln und dann die Nachricht. Jetzt funktioniert es !

**Comment by MiRo1310** [comment]
das ist komisch

**Comment by raschy** [comment]
Ich habe gerde nochmal den Text geändert. Hat auch funktioniert. Da kannst du jetzt Wochenende machen.

**Comment by MiRo1310** [comment]
Oh Wochenende noch lange nicht, ich baue jetzt gerade eine checkbox für jeden User das dieser deaktiviert werden kann
