### ISSUE TITLE
"Eintrag wurde nicht gefunden" - Option zum Deaktivieren

### ISSUE THREAD

**Issue by Schmakus** [MiRo1310/ioBroker.telegram-menu#34]
Beim senden eines Befehls, welchen der Adapter nicht kennt, erscheint die Meldung "Eintrag wurde nicht gefunden".
Es sollte eine Checkbox in den Einstellungen vorhanden sein, um diese Meldung zu unterbinden.

Gerade wenn weitere eigene Menüs eingesetzt werden, stört diese Meldung.

**Comment by MiRo1310** [comment]
Man kann dann einfach den Text in den Einstellugen entfernen und schon kommt der Text nicht mehr

**Comment by Schmakus** [comment]
> Man kann dann einfach den Text in den Einstellugen entfernen und schon kommt der Text nicht mehr

Hä, aber den Text benötige ich, um das Menü aufrufen zu können?!

![Xnip2023-07-19_14-46-39](https://github.com/MiRo1310/ioBroker.telegram-menu/assets/8231359/cfa9502a-71a1-45e6-8295-ab5d6c720164)
![IMG_2244](https://github.com/MiRo1310/ioBroker.telegram-menu/assets/8231359/6136191a-e384-431a-8502-da2c9ec0d543)

**Comment by Schmakus** [comment]
> Man kann dann einfach den Text in den Einstellugen entfernen und schon kommt der Text nicht mehr

Wo finde ich das in den Einstellungen?

**Comment by MiRo1310** [comment]
![grafik](https://github.com/MiRo1310/ioBroker.telegram-menu/assets/68854794/0aac8799-2acb-4015-8b46-de35a08f3880)

**Comment by Schmakus** [comment]
> ![grafik](https://user-images.githubusercontent.com/68854794/254577563-0aac8799-2acb-4015-8b46-de35a08f3880.png)

Ich habe diese Einstellung nicht! Ist das in v0.3.0? Ist diese im latest?

**Comment by MiRo1310** [comment]
Im latest ist noch nichts, der Pull Request ist noch offen. 
Es kann sein das die Einstellung nach der 0.3.0 eingebaut wurde.
