### ISSUE TITLE
Telegram-Adapter Restart löst Befehl aus

### ISSUE THREAD

**Issue by Schmakus** [MiRo1310/ioBroker.telegram-menu#35]
Wenn der Telegram-Adapter neu startet (z.B. jede Nacht), dann wird mein erster "Call Text" gesendet.
Das stört, wenn sonst eigentlich ein anderes Menü zuletzt geöffnet war.

**Comment by MiRo1310** [comment]
Ja werde ich mir anschauen!

**Comment by MiRo1310** [comment]
Habe es angepasst
