### ISSUE TITLE
The menu does not work above version 0.6.4

### ISSUE THREAD

**Issue by Alex18081** [MiRo1310/ioBroker.telegram-menu#50]
The menu does not work above version 0.6.4. I checked on several different servers, on all
Node.js: v18.17.0
NPM: 9.6.7
Iobroker and js version are current

**Comment by MiRo1310** [comment]
Ein bisschen mehr Information wäre gut.

**Comment by Alex18081** [comment]
> Ein bisschen mehr Information wäre gut.

Na ja.. es wird nur Start Menü angezeigt, auf einzelne Batten wird zwar reagiert aber nur als Text, Menü selbst bleibt unverändert

**Comment by MiRo1310** [comment]
Was sagt das log ? 
mach mal ein paar Screenshots von deiner config im Adapter und von Telegramm wo es nicht geht.

**Comment by Alex18081** [comment]
im log ist Error vom Telegram instance:  Error: ETELEGRAM: 400 Bad Request: message text is empty
![Screenshot_20](https://github.com/MiRo1310/ioBroker.telegram-menu/assets/20165670/59100f9e-6d28-4da2-bfa0-4fda983b000d)

![Screenshot_21](https://github.com/MiRo1310/ioBroker.telegram-menu/assets/20165670/f7b09111-6b85-4d25-9940-ea9f8c8d4216)

**Comment by MiRo1310** [comment]
Ist das Problem erst aufgetreten nachdem du den js-Controller geupdatet hast? 
Zeig mal die config im Adapter

**Comment by Alex18081** [comment]
> Ist das Problem erst aufgetreten nachdem du den js-Controller geupdatet hast? Zeig mal die config im Adapter
Nein, nicht als ich js-Controller geupdatet sondern telegram-menu Adapter, also wenn ich ich jetzt telegram-menu auf v0.6.4 Downgrade wird wieder alles funktionieren.
![Screenshot_22](https://github.com/MiRo1310/ioBroker.telegram-menu/assets/20165670/edd2ec3f-a2ff-403a-945e-7c95af0f1fc9)

**Comment by MiRo1310** [comment]
Ich kann das Verhalten leider nach nachvollziehen, stell bitte einmal den Adapter auf debug log und poste das log

**Comment by Alex18081** [comment]
[telegram-menu-debug.zip](https://github.com/MiRo1310/ioBroker.telegram-menu/files/12694059/telegram-menu-debug.zip)

**Comment by MiRo1310** [comment]
Kannst du mal schauen ob ein Fehler in der Console im Browser auftritt, evtl. lösche mal den cache.

**Comment by Alex18081** [comment]
> Kannst du mal schauen ob ein Fehler in der Console im Browser auftritt, evtl. lösche mal den cache.

Habe jetzt nicht ganz verstanden... ich nutze Telegram doch nicht im browser, nur app (Smartphone/PC/Mac)

**Comment by MiRo1310** [comment]
Bei dir werden die User im log garnicht angezeigt, daher kann es ein Fehler beim Speichern der Einstellungen des Adapters sein. Diese Daten kommen ja aus dem Frontend, also dem Browser.

**Comment by Alex18081** [comment]
> Bei dir werden die User im log garnicht angezeigt, daher kann es ein Fehler beim Speichern der Einstellungen des Adapters sein. Diese Daten kommen ja aus dem Frontend, also dem Browser.

ok..  das war ein Stoß in richtige Richtung) Habe jetzt User neu eingetragen und ein hacken bei "Text wird gesendet, wenn kein Eintrag gefunden wurde!" gesetzt und Menü hat wieder angefangen zu funktionieren.
Danke!

**Comment by MiRo1310** [comment]
Top. Dann schließe ich das Issue vorerst mal.
