### ISSUE TITLE
Datum/Uhrzeit eines Datenpunkts formatiert anzeigen lassen bzw. um rechnen

### ISSUE THREAD

**Issue by Patrick-Walther** [MiRo1310/ioBroker.telegram-menu#60]
Hallo,

ich möchte mir einen Datenpunkt [Datum/Uhrzeit] anzeigen lassen, bisher zeigt er nur die Zeit seit 1970 an.

Vielen Dank

Patrick

**Comment by MiRo1310** [comment]
![grafik](https://github.com/MiRo1310/ioBroker.telegram-menu/assets/68854794/7d0478c8-caaa-48b1-b0fa-17706b2f966b)
Bitte einmal testen

**Comment by Patrick-Walther** [comment]
danke, funktioniert super.
