### ISSUE TITLE
Action trigger lost, when edit action

### ISSUE THREAD

**Issue by boergegrunicke** [MiRo1310/ioBroker.telegram-menu#61]
**Describe the bug**  
When editing a previously defined action, it loses the selected trigger. When hitting save, this is also removed in the data and the action is not doing anything anymore, as it does not have trigger.

**To Reproduce**  
1. Go to 'action'
2. Add an action and hit save
3. Find the newly created action in the list and click the edit button 
4. change something and save again
5. trigger command lost(!)

**Expected behavior**  
The previously selected command should not be changed as long as not explicitly done by the user.

**Comment by MiRo1310** [comment]
Which version is used?
If it is stable 0.6.7 please set it to latest or download it directly from github. I fixed the problem with 0.6.8, otherwise I can't reproduce the behavior.
