### ISSUE TITLE
Bei GetState geht der Text beim Editieren verloren

### ISSUE THREAD

**Issue by Willi-Wunder** [MiRo1310/ioBroker.telegram-menu#63]
Wenn man bei GetState die Aktion editieren möchte, geht der Text verloren. Habe alle Auslöser mit "change{"true":"an", "false":"aus"}" versehen, diese werden dann nur noch mit "change{" angezeigt. Verwende die Version 0.7.1.
![Telegram_Aktion](https://github.com/MiRo1310/ioBroker.telegram-menu/assets/77007062/d960d00d-cb63-4ab8-81db-bec28fb1d897)
![Telegram](https://github.com/MiRo1310/ioBroker.telegram-menu/assets/77007062/2229c601-7f9a-4f90-a8a5-8bdca6040fed)

**Comment by MiRo1310** [comment]
Ich habe das mal angepasst, jetzt werden automatisch aus doppelten Anführungszeichen einfache, also nicht wundern, ich hoffe das alles geht, sonst bitte melden

**Comment by Willi-Wunder** [comment]
Hi, mega, das ging ja schnell. Einträge bleiben jetzt erhalten, werde die Funktion noch testen. Müssen die Zeichen in der Doku noch angepaßt/ geändert werden?

**Comment by MiRo1310** [comment]
Nein müssen Sie nicht , denn die Funktion baut es automatisch um.
