### ISSUE TITLE
Submenu funktioniert nicht

### ISSUE THREAD

**Issue by vibraHome** [MiRo1310/ioBroker.telegram-menu#64]
Telegramadapter v2.0.1
Telegram-Menu-Adapter v0.7.1

Wenn ich versuche ein Submenu aufzurufen, reagiert dieses nicht.

Die Navigation sieht folgendermassen aus:
menu:switch-ein.true-aus.false:essz:

Die Aktion:
essz   sonoff.0.Esstischlampe.POWER    !      Jetzt &&     true     false

Ich kann das Submenü aufrufen. Wenn ich dann auf "ein" oder "aus" drücke, bleibt Telegram kurz mit "Lädt" stehen.
Mehr passiert nicht.

Unterm Telegramadapter bei "request" wird der Wert "[Thomas]menu:first:essz" gesetzt.
Im Log steht dann unter Telegram-menu "Error1 {}"

Was mach ich falsch?
Im Voraus besten Dank

Thomas

**Comment by MiRo1310** [comment]
Welche Version ist installiert? Bitte einmal die latest 0.7.2 probieren. Habe da etwas geändert gehabt.

**Comment by MiRo1310** [comment]
Am besten mal einmal direkt von github installieren, habe gerade den code angepasst für die error.log ausgabe

**Comment by vibraHome** [comment]
Guten Morgen,

ich hab jetzt die Version 0.7.2 von github installiert.
Jetzt funktioniert das Schalten der Datenpunkte.
Vielen Dank für deine Bemühungen
