### ISSUE TITLE
TypeError:`` backMenuFunc V0.8.3

### ISSUE THREAD

**Issue by deg0** [MiRo1310/ioBroker.telegram-menu#65]
Moin MiRo,

vielen Dank erstmal für deine Arbeit. 
Habe vorhin von der Version 0.7.1 auf die 0.8.3 geupdatet, wegen dem Submenü bug.
Nun bekomme ich folgende Fehlermeldung im Log und die Menü im Telegram funktionieren nicht mehr:

`"TypeError: backMenuFunc is not a function\n at /opt/iobroker/node_modules/iobroker.telegram-menu/main.js:131:10\n at Array.forEach (<anonymous>)\n at /opt/iobroker/node_modules/iobroker.telegram-menu/main.js:130:31\n at Array.forEach (<anonymous>)\n at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.telegram-menu/main.js:125:19)"`

Hast du eine Idee, was das Problem ist? Danke dir!

**Comment by MiRo1310** [comment]
Hast du von Github installiert oder latest im iobroker ?

**Comment by deg0** [comment]
Von Github. Latest im iobroker ist ja noch leider die 0.7.1

**Comment by MiRo1310** [comment]
Das kann nicht latest muss die 0.8.3 sein. Ich habe irgendwo die Funktion nicht richtig benannt. Ich schaue mal ob ich den Fehler so auf die Schnelle finde.

**Comment by MiRo1310** [comment]
@deg0 installiere noch mal von Github. Der Fehler müsste weg sein

**Comment by MiRo1310** [comment]
Stable ist die 0.7.1

**Comment by deg0** [comment]
Super - der Fehler ist weg! Vielen Dank für den schnellen fix!
