### ISSUE TITLE
Anlegen von Aktionen

### ISSUE THREAD

**Issue by michihorni** [MiRo1310/ioBroker.telegram-menu#71]
Hallo ich beschäftige mich mit deinem Adapter V 0.8.3.
Habe die Standards der Auslöser übernommen.
Bei Aktionen kann ich als Trigger 1x Iobroker auswählen, beim Anlegen der zweiten Aktion, ist der Trigger Iobroker nicht mehr zu sehen.
Alle Trigger die einmal gebraucht wurden sind im Auswahlfeld verschwunden.
Das auswählen der ID dauert sehr lange, es fällt mir auf, dass beim Beschreiben der ID, der Adapter schon wieder das Auswahlfeld für ID öffnet.
Gruß Michael

**Comment by MiRo1310** [comment]
Das die trigger verschwinden ist auch Sinn und Zweck der Sache. Jeder trigger darf nur einmal benutzt werden. 
zu 2 am besten mal Screenshots dazu.

**Comment by michihorni** [comment]
Hallo

ich habe auf meiner Testmaschine mal einen Trigger und drei Aktionen realisieren können. Der Umzug der Installation auf meine Life Maschine hat dann die genannten Probleme bereitet.

Ich würde es toll finden wenn du die Gruppenbildung durch einen Trigger realisieren könntetst.

Zu Punkt zwei versuche ich mal einen Screenshot zusenden, vielleicht klappt das heute noch.


 

Mit freundlichen Grüßen
M. Horn

 
 

Gesendet: Freitag, 03. November 2023 um 05:15 Uhr
Von: "MiRo1310" ***@***.***>
An: "MiRo1310/ioBroker.telegram-menu" ***@***.***>
Cc: "michihorni" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [MiRo1310/ioBroker.telegram-menu] Anlegen von Aktionen (Issue #71)


 

Das die trigger verschwinden ist auch Sinn und Zweck der Sache. Jeder trigger darf nur einmal benutzt werden.
zu 2 am besten mal Screenshots dazu.

**Comment by MiRo1310** [comment]
Du kannst mit einem trigger mehrere Daten abfragen oder auch setzen. 
Was genau möchtest du machen?

**Comment by michihorni** [comment]
Ich möchte gerne Werte meiner PI's abfragen, wie z.B CPU Auslastung, Verfügbarer Speicher und UpTime Zeit,

oder im Garten mehrere TUYA Geräte auf einmal schalten.
 

Mit freundlichen Grüßen
M. Horn

 
 

Gesendet: Freitag, 03. November 2023 um 09:46 Uhr
Von: "MiRo1310" ***@***.***>
An: "MiRo1310/ioBroker.telegram-menu" ***@***.***>
Cc: "michihorni" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [MiRo1310/ioBroker.telegram-menu] Anlegen von Aktionen (Issue #71)


 

Du kannst mit einem trigger mehrere Daten abfragen oder auch setzen.
Was genau möchtest du machen?

**Comment by MiRo1310** [comment]
Ja das ist doch kein Problem. Aktion erstellen oder editieren und dann gibt es einen Button für eine neue Zeile.

**Comment by michihorni** [comment]
Danke, dass habe ich übersehen. Danke für den tollen Adapter und den schnellen Support
 

Mit freundlichen Grüßen
M. Horn

 
 

Gesendet: Freitag, 03. November 2023 um 10:07 Uhr
Von: "MiRo1310" ***@***.***>
An: "MiRo1310/ioBroker.telegram-menu" ***@***.***>
Cc: "michihorni" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [MiRo1310/ioBroker.telegram-menu] Anlegen von Aktionen (Issue #71)


 

Ja das ist doch kein Problem. Aktion erstellen oder editieren und dann gibt es einen Button für eine neue Zeile.

**Comment by MiRo1310** [comment]
Besteht noch weiterhin ein Problem? 
Bald kommt sowieso ein komplett neues UI.

**Comment by michihorni** [comment]
Guten Morgen, Der Adapter tut was er soll. Dankeschön. Bin sehr auf das neue UI gespannt --Gruß Michael Horn Am 07.11.23, 07:16 schrieb MiRo1310 ***@***.***>:

   
  Besteht noch weiterhin ein Problem? Bald kommt sowieso ein komplett neues UI.

**Comment by MiRo1310** [comment]
Können wir das Issue schließen?

**Comment by michihorni** [comment]
Ja klar, kannst Du das tun oder kann ich das tun?--Gruß Michael Horn Am 10.11.23, 20:56 schrieb MiRo1310 ***@***.***>:

   
  Können wir das Issue schließen?
