### ISSUE TITLE
GetState speicherung nur nach Abbruch möglich

### ISSUE THREAD

**Issue by quorle** [MiRo1310/ioBroker.telegram-menu#72]
Erst nach Abbruch der Einstellung und neues Öffnen der Einstellung kann gespeichert werden.

![Telegram Menü Fehler](https://github.com/MiRo1310/ioBroker.telegram-menu/assets/38273154/0c8f6dd3-6bb7-47be-857f-ed646f7398b2)

**Versions:**  
 - Adapter version: v0.8.5
 - JS-Controller version: 5.0.16
 - Node version: v18.18.2

**Comment by MiRo1310** [comment]
Ist doch klar das du nicht speichern kannst da du nicht komplett ausgefüllt hast

**Comment by quorle** [comment]
Selbst wenn alle Felder ausgefüllt sind, kann man nur speichern wie oben gezeigt.

**Comment by MiRo1310** [comment]
ich habe die neue UI online, du kannst gerne testen
