### ISSUE TITLE
Zusätzlich Parsmode als HTML

### ISSUE THREAD

**Issue by quorle** [MiRo1310/ioBroker.telegram-menu#73]
Future Request....

Kann man den Parsmode "HTML" hinzufügen? Dadurch kann man den etwas bearbeiten (Fett, unterstrichen, ....)
Ich nutze das eigentlich in jeder Nachricht, damit kann man die Nachrichten schöner formatieren.

**Comment by MiRo1310** [comment]
Kannst du mal ein paar mehr Infos geben? Wie machst du das genau?

**Comment by quorle** [comment]
Das ganze sieht so als Blockly aus:

![Unbenannt](https://github.com/MiRo1310/ioBroker.telegram-menu/assets/38273154/7159bdb4-31d2-4488-8101-121a4cb1ff72)


Diese Varianten gibt es:

```
<b>Text</b>
Text fett formatieren
```
```
<i>Text</i>
Text kursiv formatieren
```
```
<a href=“URL“>Link</a>
Link einfügen
```
```
<code>Quelltext</code>
Text als Quelltext formatieren
```

**Comment by MiRo1310** [comment]
Ich habe mir das gerade mal angeschaut, müsste man ja eigentlich für jede Row sepearat einstellen, oder global? Global ist glaube ich nicht schön.
