### ISSUE TITLE
Abfrage des Standorts

### ISSUE THREAD

**Issue by BobBruni** [MiRo1310/ioBroker.telegram-menu#82]
Abfrage des Standorts mit dieser Funktion:

![image](https://github.com/MiRo1310/ioBroker.telegram-menu/assets/58072812/d5868fb1-556d-4195-9412-3eafd6b41e04)

**Comment by MiRo1310** [comment]
Die Werte werden aber von Daten punkten geliefert? So wie oben? Also braucht man einen Trigger und dann zwei IDs zum eingeben und schon würde es gehen. Oder ist dein Gedanke ein anderer?

**Comment by BobBruni** [comment]
Korrekt. Einen Trigger und zwei IDs für Längen- und Breitengrad.
