### ISSUE TITLE
Zeilenumbruch im Text erzwingen

### ISSUE THREAD

**Issue by Willi-Wunder** [MiRo1310/ioBroker.telegram-menu#83]
Wenn man bei Navigation - Text mehrere Status Abfragen einfügen kann, wäre es super wenn man dann auch einen Zeilenumbruch zwecks der Übersicht erzingen kann.

![Text erweitern](https://github.com/MiRo1310/ioBroker.telegram-menu/assets/77007062/a7f1598f-f5df-47a5-9013-85da53662aad)

**Comment by liv-in-sky** [comment]
irgenein sonderzeichen für neue zeile wäre echt gut :-)
