### ISSUE TITLE
Implementierung "Binding of objects"

### ISSUE THREAD

**Issue by BobBruni** [MiRo1310/ioBroker.telegram-menu#85]
Readme:
https://github.com/ioBroker/ioBroker.vis#bindings-of-objects

Damit lassen sich mit Datenpunkten operationen durchführen oder auch z.b. Zeitstempel bzw. letzte Änderung eines Datenpunktes anzeigen: 

Last change: {objectRed.lc;date(hh:mm)}

**Comment by MiRo1310** [comment]
Kannst du mir genau sagen was du damit machen möchtest?

**Comment by BobBruni** [comment]
**Zeit der letzten Änderung des Datenpunktes in einem bestimmten Format**
{tr-064.0.devices.Nutzer.active.lc;date(hh:mm)}

Wenn ich für diesen Datenpunkt die Funktion {time} verwende - bekomme ich 01.01.1970 01:00:00 zurück.

**Bedingungen**
{h:javascript.0.Licht.Status.Anzahl_ein; h >=2 ? "Lichter" : h ==1 ? "Licht" : "Alle Lichter aus!"}
{wert1:shelly.0.SHSW-PM#76E928#1.Relay0.Switch;wert2:javascript.0.scriptEnabled.common.Steckdose.Auto_Charge; wert1 == false ? "battery-off-outline" : wert2 == true ? "battery-charging-50" : "battery-positive"}

Damit wäre man sehr flexibel, was die Datenausgabe angeht

**Comment by MiRo1310** [comment]
Das mit dem Zeitstempel habe ich verstanden. Aber wozu die Bedingungen ? Ich komme da noch nicht so ganz hinter.

**Comment by BobBruni** [comment]
Ich lasse mir z.b. eine Liste mit den Räumen ausgeben, in welchen Licht brennt.
Hier würde mir die Bedingung helfen um die Ausgabe korrekte darzustellen.

{h:javascript.0.Licht.Status.Anzahl_ein; h >=2 ? "eingeschaltene Lichter" : h ==1 ? "eingeschaltenes Licht" : "Alle Lichter aus!"}

![image](https://github.com/MiRo1310/ioBroker.telegram-menu/assets/58072812/52652697-4ff3-469e-8b82-2a89c7b8bc7a)

Hab jetzt leider kein besseres Beispiel, aber man damit sehr viele Möglichkeiten...

**Comment by MiRo1310** [comment]
Okay. Aber das sind 2 einzelne Funktion die nicht direkt miteinander verknüpft sind?

**Comment by BobBruni** [comment]
Korrekt

**Comment by MiRo1310** [comment]
Der erste Teil ist erledigt
