### ISSUE TITLE
Change Befehl klappt nicht bei mehreren Status Abfragen

### ISSUE THREAD

**Issue by Willi-Wunder** [MiRo1310/ioBroker.telegram-menu#86]
Hi,
wie bereits im Forum geschrieben, klappt die Umwandlung "true" + "false" nicht mehr, wenn mehrere Status Abfragen sind. Beide Werte werden im DP als boolean ausgegeben. Hab die beiden Datenpunkte von der Reihenfolge mal getauscht, der erste wird immer richtig gewandelt, der zweite dann nicht mehr. Aktuelle Version 1.1.0.
`Zirku ein- oder ausschalten?  \n Aktueller Status Zirku Single: {status:javascript.0.scriptEnabled.common.Zirkulation_ein_WP_WW_Single'} \n Aktueller Status Zirku Familie: {status:javascript.0.scriptEnabled.common.Zirkulation_ein_WP_WW_Familie'} change{'true':'EIN','false':'AUS'}`
![Zirku_Tele](https://github.com/MiRo1310/ioBroker.telegram-menu/assets/77007062/17bf793d-dd5e-4767-8f18-ebb8230d9a69)
![Zirku_Tele-beide](https://github.com/MiRo1310/ioBroker.telegram-menu/assets/77007062/34756abb-8680-41f9-aeff-020b37e0c279)

**Comment by MiRo1310** [comment]
ich kann dir jetzt schon sagen wo das Problem liegt, bin gerade dabei es nach zu stellen, aber du musst für jede id ein eigenes change machen. ich werde es zwar jetzt noch mal selbst testen und mich noch mal melden

**Comment by MiRo1310** [comment]
Ja genau das ist es, wie gesagt für jeden status ein change, die id durchlaufen eine schleife die erste id sucht nach dem ersten aufkommen des change, du kannst auch beide change am ende machen, das erste ist für id 1 und das zweite für id2. sinn macht es , denn du könntest 2 verschiedene ids abrufen, einmal number und z.b. boolean, so bist du flexibel und kannst für beide es sinnvoll einstellen.
