### ISSUE TITLE
Datenpunkt als Auslöser für Navigation

### ISSUE THREAD

**Issue by BobBruni** [MiRo1310/ioBroker.telegram-menu#87]
Ich lasse mich über diverse Ereignisse über Telegram informieren.
Der Wunsch wäre, direkt auf diese Meldungen in Form eines Submenüs reagieren zu können.

Zwei Beispiele:

Meldung: Achtung Garagentor noch geöffnet!
Option: Garagentor schließen?

Meldung: Es sind noch die diverse Lichter angeschalten!
Option: Alle ausschalten?

Hätte man die Möglihckeit bei Navigation einen Datenpunkt als Trigger auszuwählen, wäre das möglich.
Man könnte sich so im Adapter die Submenüs bequem zusammenbauen und bei entsprechender Sitaution per Datenpunkt triggern.

**Comment by MiRo1310** [comment]
Was mir dazu in den Sinn kommt ist, ich erstelle ein neues tab mit Namen Events. Darin gibt man die ID an auf welchen Datenpunkt getriggert werden soll und das Zielmenu und fertig, dieses erstellt man unter Navigation und kann es auch anderweitig nutzen.

**Comment by MiRo1310** [comment]
Und natürlich müssen wir noch die Bedingung mit einbinden

**Comment by BobBruni** [comment]
Die Flexibiltät wär Wahnsinn!

**Comment by MiRo1310** [comment]
Ich bin schon dran, solange wie es regnet

**Comment by BobBruni** [comment]
Hier wärs dann auch noch gut, wenn man den **Submenü Switch** anpassen würde, dass man von 1 bis beliebig Schaltflächen erstellen kann...

 menu:switch-wert1.true-wert2.false-wert3.false:name:

**Comment by MiRo1310** [comment]
Ja das wäre ok #88

**Comment by MiRo1310** [comment]
Ich habe die Daten gerade mal hoch geladen, das war garnicht so einfach, ich hoffe es läuft. Probe versuche liefen. Du kannst ein normales Menu schicken oder ein Submenu.
