### ISSUE TITLE
Tab für E-Charts Diagramme

### ISSUE THREAD

**Issue by BobBruni** [MiRo1310/ioBroker.telegram-menu#92]
Man kann sich in E-Charts erstellte Diagramme per Telegram schicken lassen.
![image](https://github.com/MiRo1310/ioBroker.telegram-menu/assets/58072812/77397ad1-179b-4517-9921-dca9bc679827)

Doku:  [https://github.com/ioBroker/ioBroker.echarts](url)
Beispiel: [https://www.smarthome-tricks.de/software-iobroker/iobroker-e-charts-diagramme-per-telegram-nachricht-versenden/](url)

Genial wäre es, dies direkt im Telegram-Menu-Adapter (unter einem neuen Tab) einstellen zu können.

**Comment by MiRo1310** [comment]
Werde ich in Angriff nehmen
