### ISSUE TITLE
Bitte eine Scrollbar für die Seitenauswahl einfügen

### ISSUE THREAD

**Issue by quorle** [MiRo1310/ioBroker.telegram-menu#93]
Ich habe jede Seite einzeln angelegt (Pro Raum eine Seite). Leider gibt es in der Seitenauswahl keine Scrollbar, somit kann ich nicht alle Seiten bearbeiten.

Hier ein kleiner Ausschnitt, der nach unten weiter gehen sollte:

![Unbenannt](https://github.com/MiRo1310/ioBroker.telegram-menu/assets/38273154/ece478b6-1643-4eb7-8975-09733496a36b)

**Comment by MiRo1310** [comment]
😂 ja ich werde da was machen
