### ISSUE TITLE
Menu_number wird nicht richtig übermittelt

### ISSUE THREAD

**Issue by Willi-Wunder** [MiRo1310/ioBroker.telegram-menu#94]
Hallo Michel,

beim "menu:dynSwitch" werden keine "0.5" Schritte angezeigt.
![Flex-Menü-iobroker](https://github.com/MiRo1310/ioBroker.telegram-menu/assets/77007062/fef1e544-bb1a-4fa0-92fe-e55c19940356)
Wählt man diese aus, wird der Wert 5 übermittelt
![Flex-Menü](https://github.com/MiRo1310/ioBroker.telegram-menu/assets/77007062/5160be0d-dba7-4b80-942b-e10a572b9a5d)

Hatte hier zuerst das "menu:number26.5-29.5-0.5" genommen, allerdings fängt er nicht mit dem Startwert 26.5 an. Wollte hier den Zeilenumbruch vermeiden.
![Navi-Heizkurve-Parallel_tele](https://github.com/MiRo1310/ioBroker.telegram-menu/assets/77007062/edef9751-8ec0-4d69-a1e1-2694e8715afd)
![Navi-Heizkurve-Parallel](https://github.com/MiRo1310/ioBroker.telegram-menu/assets/77007062/44ba750a-2e7e-4b63-a344-adf6f3ffffa1)

Was auch komisch war, dass wenn ich bei der "Parallelverschiebung" die zwei Werte mit x.5 einstelle, das Menü nicht angezeigt wird. 
![Navi-Heizkurve-Parallel](https://github.com/MiRo1310/ioBroker.telegram-menu/assets/77007062/013f3bae-c3e7-4eeb-b6c8-20c8c99fc365)
![Navi-Heizkurve-Parallel_tele](https://github.com/MiRo1310/ioBroker.telegram-menu/assets/77007062/ffdf9c99-d680-45af-b5cc-109df0cbb1ac)

Ändere ich bei "Parallelverschiebung" einen Wert auf 1-stellig, wird das Menü wieder angezeigt. ABER: Bei der "Heizkurve" funktioniert es mit auch zwei x.5 Werten.
![Telegram_Menu_ohne komma](https://github.com/MiRo1310/ioBroker.telegram-menu/assets/77007062/ea6b1c96-0a9a-401f-9aac-81c6d08aa4c7)
![Telegram_Menu_ohne komma_telegram](https://github.com/MiRo1310/ioBroker.telegram-menu/assets/77007062/a0a26b6f-7054-4470-9294-d50fe195b587)

Hoffe ich konnte es verständlich rüber bringen :-)

**Comment by MiRo1310** [comment]
Zu 1. dynSwitch, ja das ist etwas unglücklich programmiert, wenn ich das ändere muss ich ein Breaking Change machen. Dann müssten alle Menus damit vom angepasst werden. Würde aber gehen
Zu 2. menu:number habe ich gerade angepasst und hoch geladen

Um Problem 1 kümmere ich mich, habe dazu ein seperates Issue erstellt
